### ISSUE TITLE
Profiling not working with Adobe Scout and AIR 33.1.1.554 on Android

### ISSUE THREAD

**Issue by mwelk** [airsdk/Adobe-Runtime-Support#1011]
## Problem Description

Adobe Scout does not receive any profiling information from an application compiled with AIR 33.1.1.554 on Android 11/12.
It does not make any difference if the app is compiled as AAB or APK.

The Scout app itself can connect to the Adobe Scout Host. 

## Environment:
- SDK: AIR 33.1.1.554
- OS: Android 11 and 12
- Package-Type: APK and AAB

**Comment by ajwfrost** [comment]
The Scout companion app is trying to share the preferences via `MODE_WORLD_READABLE` but:
> Starting from Build.VERSION_CODES.N, attempting to use this mode throws a SecurityException.

We're looking to see if we can get access to the Scout app and update it..

It's meant to be possible to store a telemetry.cfg file into the package with the settings but this appears to have an issue currently - but we can at least address this in the short term to have a way to do this!

**Comment by mwelk** [comment]
Thanks for the update and looking forward to your solutions!

**Comment by ajwfrost** [comment]
Actually .. the issue I thought was with telemetry.cfg appears to be with another bit of code that's not yet released, so it should work if you can include this in your package. So just create a file like the below called telemetry.cfg and include this as a file at the root of your Android project (e.g. where the swf file normally goes). Assuming the IP address is correct and reachable, it should then work...
```
TelemetryAddress=NNN.NNN.NNN.NNN:7934
SamplerEnabled = true
CPUCapture = true
DisplayObjectCapture = false
Stage3DCapture = true
ScriptObjectAllocationTraces = true
```
Please let us know if that doesn't work; we've checked it on an emulated Pixel with API 30 / Android 11..
thanks

**Comment by mwelk** [comment]
It's working this way on API 30 / Android 11 and 12, thanks!
Now we have at least an option to profile on devices again. But it would be good to configure options with the companion app in the future to not hard code a single ip address as we have multiple testers using Adobe Scout.

**Comment by megajogos** [comment]
Hi, ajwfrost.

We use scout in a lot of computers. How to work with multiple IPs ?

**Comment by ajwfrost** [comment]
Currently the only way that this can work is to package the app with the telemetry file per the above, where the telemetry file needs to have the IP address -> so you would need multiple packages, or to re-package each time you wanted to use Scout from a different machine.

We are in the process of trying to arrange to get the Scout companion app source code so that we can update it to not use the old/restricted paths for storing the telemetry file. But since this is taking a bit of time, we can perhaps look at an intermediate approach. Would you be able to confirm what sort of mechanisms you could use for configuring devices: is it possible to connect them to ADB and run a command from there, in order to kick off the testing or to configure the telemetry details? Or would it need to be something that's purely done from the handset UI like the existing companion app?

thanks

**Comment by megajogos** [comment]
Any news about it?

**Comment by ajwfrost** [comment]
It's been a slow process but we'll be launching a new version of the Scout companion app shortly; we also then need to update the AIR runtime so that the two can communicate properly using Android 12 etc.. it's all working, but in our "future" release which we hope to push out as a preview soon. Only caveat is that we need to have a minimum Android API level of 16 with this...

thanks

**Comment by ajwfrost** [comment]
So .. when we do our next SDK release, I'll add the details to that, but our version of the Scout companion app for Android is now live:
https://play.google.com/store/apps/details?id=com.harman.air.scout.companion

It contains the same code as before that will allow AIR apps to pick up the settings if they're using older Android versions; for the new Android versions we need the next SDK release that will then bring in the service connection required so that the runtime can find out where to connect to... 

thanks

**Comment by ajwfrost** [comment]
Final update for this thread -> the new version of AIR SDK, 33.1.1.856, has got the necessary runtime updates so that even on Android 11 or 12, it will be able to connect to the new (Harman version of) Adobe Scout.

thanks
