### ISSUE TITLE
How to create an Air Native Extensions for Linux ?

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#1022]
Hello,

adt has a new target ane -platform "Linux-x86-64" since Air 33.1.1.533, but how to create an Air Native Extensions for Linux (Ubuntu for example) ?

I tried to create a static library *.a in C like iOS (and a shared library *.so too)

```
...
void TestContextInitializer(void* extData, const uint8_t* ctxType, FREContext ctx, uint32_t* numFunctionsToTest, const FRENamedFunction** functionsToSet) {
    
    *numFunctionsToTest = 1;
    
    FRENamedFunction* func = (FRENamedFunction*) malloc(sizeof(FRENamedFunction) * *numFunctionsToTest);
    
    func[0].name = (const uint8_t*) "initTest";
    func[0].functionData = NULL;
    func[0].function = &initTest;
    
    *functionsToSet = func;
}
...
```

```
gcc -Wall -c test.c
ar crs libtest.a test.o
```

but it doesn't work ?
`error #3500: The extension context does not have a method named "initTest"`

Thanks

**Comment by pol2095** [comment]
Any help ?
is-it possible to create an Air Native Extensions on Linux `<platform name="Linux-x86-64">` ?
The library must be a static library (*.a) or a shared library (*.so) or other ? in C or C++ ?
Thanks

**Comment by ajwfrost** [comment]
Hi

It should be a dynamic/shared library, .so file. If you're using C++ then the only thing to watch out for is the name decoration, so e.g. declare any exported functions as `extern "C"`, and you'll need to ensure the init/destroy functions mentioned in the extension XML configuration are visible, so precede them with `__attribute__((visibility("default")))`

For example:
```
#ifdef WIN32
#define DLLEXPORT __declspec( dllexport )
#define NULL	0
#else
#define DLLEXPORT  __attribute__((visibility("default")))
#endif

DLLEXPORT void InitExtension(
        void**                 extDataToSet       ,
        FREContextInitializer* ctxInitializerToSet,
        FREContextFinalizer*   ctxFinalizerToSet)
{
	*extDataToSet = NULL;
	*ctxInitializerToSet = ContextInitializer;
	*ctxFinalizerToSet   = ContextFinalizer;
}

DLLEXPORT void DestroyExtension(void* extData)
{
	// not actually guaranteed to be called at all..
}
```


Looking at one of our demos, we had the build commands of:
```
gcc -fPIC -o EdgeDetect.o -c EdgeDetect.c
gcc -shared -fPIC -o EdgeDetect.so EdgeDetect.o -lc -L. -lFlashRuntimeExtensions
```
I believe the `-L.` there should probably be `-L/path/to/sdk/lib` so that it picks up the stub library from the AIR SDK, but we had copied that into the local folder for convenience...

Also just looking at your code: we don't clean up any memory so you may want to free the structure that you malloced, within the context finalizer. Or if you know all the details at compile-time then you can use static/global memory for them, e.g.
```
	static FRENamedFunction arrFunctions[] = {
		{ (uint8_t*)"detectEdges", NULL, detectEdges },
		  (uint8_t*)"get_strlen" , NULL, get_strlen  }
	};
	*functionsToSet = arrFunctions;
	*numFunctionsToSet = 2;
```
