### ISSUE TITLE
Performance drop and micro freezes on aab vs apk on AIR 33.1.1.575

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/Adobe-Runtime-Support#1050]
I built `apk armv8` and `aab` from absolutely equal codebase which works for years and tested both builds on Motorola One Action with Android 11.

On the same level of the game with `apk` build I have about 52 fps and with `aab` build I have about 45 fps and a lot of micro freezes.

Probably something packed it a weird way in `aab` file.

Maybe someone else also met this issue?

In logcat I found this type of error, but I'm not sure that it is related to this issue:

> 08-05 21:28:46.110 23037 15711 W NetworkScheduler: Error inserting flex_time=5000 job_id=-1 period=11000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=212621000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1628188126100 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) [CONTEXT service_id=218 ]

The game use @marchbold ANEs:

> androidx.appcompat 
> androidx.browser 
> androidx.cardview 
> androidx.core 
> androidx.recyclerview 
> androidx.work 
> androidx.multidex 
> androidx.room 
> androidx.vectordrawable 
> com.android.installreferrer 
> com.distriqt.Application 
> com.distriqt.ApplicationRater 
> com.distriqt.Core 
> com.distriqt.Firebase 
> com.distriqt.GameServices 
> com.distriqt.InAppBilling 
> com.distriqt.Notifications 
> com.distriqt.playservices.Ads 
> com.distriqt.playservices.AdsIdentifier 
> com.distriqt.playservices.Analytics 
> com.distriqt.playservices.Auth 
> com.distriqt.playservices.Base 
> com.distriqt.playservices.CloudMessaging 
> com.distriqt.playservices.Drive 
> com.distriqt.playservices.Games 
> com.distriqt.playservices.Location 
> com.distriqt.PushNotifications 
> com.distriqt.Share 
> com.google.android.datatransport 
> com.google.android.material 
> com.google.android.play 
> com.google.dagger 
> com.google.guava 
> com.google.firebase.core 
> com.google.protobuflite 
> com.jetbrains.kotlin

**Comment by ajwfrost** [comment]
Hi

This is interesting/concerning. I'm not sure what would affect it: the actual AIR libraries/code would be exactly the same regardless of whether you package for AAB or APK. But there are differences in how these are put together..

Are you able to check something for us: if you edit the `lib/adt.cfg` file in your SDK and uncomment the line:
```
KeepAndroidStudioOutput=true
```
and then build a bundle: you should then end up with a folder "AndroidStudioProject" that contains all the files/folders that we generated in order to get Gradle to build the bundle file.

If you open that folder in Android Studio, it should be possible for you to generate an APK file from it (in release mode i.e. "Generate signed bundle/apk"): can you see whether that one has the same characteristics as your bundle, or of the generated APK file?

If it's different from the APK then would it be possible for you to send us the two APKs so that we can check whether there are any differences in the configuration of the runtime or any supporting files? The other thing I was wondering about is the multidex approach, where when we built an APK ourselves we had a lot more control of this process, but now it's just left to Gradle to try to work out which classes to put where..

thanks

**Comment by sjabberwocky** [comment]
I localize this issue, something wrong with frequently calls of `GameServices.service.achievements.achievementStepsSet(id, steps);` from [GameServices](https://docs.airnativeextensions.com/docs/gameservices) ANE.

We have a tower defense game and many of ours achievements are related to killing enemies.
We have up to 100 enemies at the same time at the level and each killing may be reported to multiple achievements during playtime.

I will rework my achievement code to reduce number of calls for `achievementStepsSet` and it should work fine for me.

But anyway, it's interesting why `achievementStepsSet` works slower with `aab` build.

**Comment by ajwfrost** [comment]
Interesting! thanks for finding this out
@marchbold let us know if you need any profiling or are able to clarify if there's an AS3 API that's causing the slow-down..

**Comment by sjabberwocky** [comment]
To be clear, my achievement reporting code is here:
```
if (GameServices.isSupported && GameServices.service.isSignedIn() && GameServices.service.achievements.isSupported)
{
    GameServices.service.achievements.achievementStepsSet(id, steps);
}
```

Thanks to `aab` support we reduced build size by 20% and get extra 3 fps. :)

**Comment by marchbold** [comment]
That does sound odd, the `achievementStepsSet()` does do a simple Games SDK call, but I doubt it is designed to be called at a high frequency. More like a couple of times per level, so definitely reducing the frequency of this call would be recommended.
