### ISSUE TITLE
[macOS] HTMLLoader doesn't work with Apple Silicon M1 ARM CPUs devices

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1106]
## Problem Description
`HTMLLoader` doesn't work with Apple Silicon M1 ARM CPUs macOS devices.
Tested with latests AIR 33.1.1.575 with multiple macOS Big Sur Apple Silicon M1 ARM CPUs devices with different applications.
Same problem in all cases.

It works fine with Intel-based macOS devices.
Also it works fine with Windows devices.

This issue blocks `HTMLLoader` usage at all.

Related issues (not the same):
https://github.com/airsdk/Adobe-Runtime-Support/issues/1092
https://github.com/airsdk/Adobe-Runtime-Support/issues/1015
https://github.com/airsdk/Adobe-Runtime-Support/issues/178
https://github.com/airsdk/Adobe-Runtime-Support/issues/214
https://github.com/airsdk/Adobe-Runtime-Support/issues/143
https://github.com/airsdk/Adobe-Runtime-Support/issues/183
https://github.com/airsdk/Adobe-Runtime-Support/issues/337

## Steps to Reproduce
Package bundled macOS AIR application using code below launch it with Apple Silicon M1 ARM CPUs macOS device.
Note: may be you cannot use IDE to launch that because of issue https://github.com/airsdk/Adobe-Runtime-Support/issues/1092

Application example with sources attached.
[macos_htmlloader_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/7047785/macos_htmlloader_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.html.HTMLLoader;
	import flash.net.URLRequest;
	
	public class MacOSHTMLLoaderBug extends Sprite {
		private var htmlLoader:HTMLLoader;
		
		public function MacOSHTMLLoaderBug() {
			htmlLoader = new HTMLLoader();
			htmlLoader.width = 640;
			htmlLoader.height = 480;
			addChild(htmlLoader);
			
			htmlLoader.load(new URLRequest("https://google.com"));
		}
	}
}
```

**Actual Result:**
Runtime error will be thrown:
```
Exception: flash.html::ControlInitializationError
	flash.html::HTMLLoader/initHTMLEngine
	flash.html::HTMLLoader
	MacOSHTMLLoaderBug
	runtime::ContentPlayer/loadInitialContent
	runtime::ContentPlayer/playRawContent
	runtime::ContentPlayer/playContent
	runtime::AppRunner/run
	AppEntryCommon/run
	global/runtime::ExtendedAppEntry
	global/runtime::CaptiveAppEntry
```
Website (specified URL) cannot be loaded and shown.

**Expected Result:**
Application correctly load and show specified URL.

## Known Workarounds
none

**Comment by rogerclarkmelbourne** [comment]
No. 
It's not deployed though the App store becuase of  a problem with using a ANE which Apple's validation won't accept due to the way the static library was compiled 

Its deployed via an installer package

**Comment by itlancer** [comment]
> If you have an application that you can configure to always use Rosetta then it should work; we're looking to see what sort of workarounds may be possible to try to make this automatic..

@ajwfrost, we cannot use Rosetta for whole application cause we already switch to some universal native extensions and I think it better for further development avoid Rosetta. Maybe only WebKit.dylib somehow could use Rosetta "under the hood"? Or it could be recompiled to support arm64?
Ideally we need new webframe functionalities implementation for AIR. To support using it with `DisplayList` (or even `Stage3D` too) and with latest (may be native/system libraries from device) HTML5/CSS3 specifications. Right now `HTMLLoader` and `StageWebView` outdated and all alternative approaches with native extensions for that have some limitations.

**Comment by rogerclarkmelbourne** [comment]
@ajwfrost 

FYI.

I've built a version which doesn't check the Capabilities.OS in order to determine the the OS, and uses a CONFIG constant instead

We've sent this version to the customer, but have yet to hear back from them.

I'll let you know if we ever get feedback on this, but sometimes the customers find it easier just to use the PC or iPad version instead.

**Comment by rogerclarkmelbourne** [comment]
@ajwfrost

We had another report of Capabilities.os string reporting a Mac as an iPad

We've asked this customer to confirm their hardware, because the other customer who had the problem didn't reply to our questions :-(

**Comment by paulweb2** [comment]
On a Mac M1 developing/debugging with IntelliJ IDEA an AIR/FLEX app using Harman Air SDK 33.1.1.674 overlaid on Flex SDK  4.16  results in '[Fault] exception, information=Error: HTMLLoader failed to initialize'.

Same set up works fine on an Intel Mac and the output AIR app can be installed and run using Rosetta on an M1.

Is this just never gonna work on an M1 and I should just stay developing on the Intel Mac and get M1 users to always run the app with Rosetta?

**Comment by ajwfrost** [comment]
Hi - currently this won't work because of the old WebKit library only supporting Intel. If you strip the arm64 variant out of your application's main executable, it will automatically use Rosetta on M1 and then load in the WebKit.

But we're about to push out a beta that will remove WebKit entirely, and just rely on the native OS to provide webview functionality - essentially like a `StageWebView(true)` object. The benefit of this is it will support the latest HTML5 standards; the downside is that we don't have the tight integration and control between AS3 and JavaScript/HTML any more. We can then see what integration people do actually need here, and provide some updated version of this using a better/more future-proof technology..

To clarify the proposed approach: the updated AIR runtime will still expose the HTMLLoader API but under the hood will use the native stagewebview; trying to create a StageWebView object will always create the native OS implementation. So for the vast majority of apps (and certainly the ones that Adobe use for the runtime and application installer dialogs etc) should just run fine on this without needing any changes...

thanks

**Comment by paulweb2** [comment]
Thanks Andrew will wait for the update and see how things go with the native approach.

**Comment by al-sabr** [comment]
This thread can be connected with this also : #1438

**Comment by itlancer** [comment]
With latests AIR versions `HTMLLoader` deprecated and removed. So this issue not actual anymore.
But WebKit files still in AIR application bundle https://github.com/airsdk/Adobe-Runtime-Support/issues/1882
