### ISSUE TITLE
Flash Builder error can not load UI package explorer when upgrading the AIR SDK to v33.1.1.575

### ISSUE THREAD

**Issue by blackjyn** [airsdk/Adobe-Runtime-Support#1152]
## The Problem 

Here's the problem:
![flash builder project explorer err with AIR 33 1 1 5xx](https://user-images.githubusercontent.com/6046191/133226319-b1c1ab8d-ac8c-4ef9-a27f-c36d978e9c2a.png)

## Steps to Reproduce

I just upgrading the AIR SDK inside this path that by default is used by Flash Builder as the compiler , from v32 (by Adobe) to v33.1.1.575 (by harman) .
`C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK`
**Upon upgrade the IDE can NOT  load the ui pkg explorer like the problem mentioned before.**

## Known Workarounds
Just fallback to use v32 , everything works fine but hopefully can use the latest SDK.
**Also worth to clarify , this problem does NOT occur on the Flex SDK with that equal Harman's AIR SDK for Flex.**
yep, just when upgrading the AIR SDK only.

## ENV
- Win x64 8.1
- Flash Builder 4.7 x64
- AIR SDK v33.1.1575 ASC2

**Comment by ajwfrost** [comment]
What version of Java have you got in
```
C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\jre
```
as this would likely need to be Java 1.8 or later...

thanks

**Comment by blackjyn** [comment]
Godness, I don't realize that FB 4.7 still shipping with JRE 1.6! 
![fb47 jre6](https://user-images.githubusercontent.com/6046191/133331296-fed7de61-9da4-4503-a3db-c5095ae22e5e.png)

Strangely , setting JRE 8 to use from `Windows>preferences` doesn't work!

It is solved now by upgrading the JRE (not the JDK) to JRE 1.8  manually, you can obtain from https://www.java.com/en/download/manual.jsp
or if you have Java 8 installed you can copy that JRE to FB by overriding it.

![fb47 air 33 working with jre8](https://user-images.githubusercontent.com/6046191/133332967-2a7b9aed-c0c4-4ce8-825a-974e61a099e4.png)

**Comment by SD216814** [comment]
@ajwfrost hi, I meet the same issues on Mac. 
But I cannot find the jre embeded in the FlashBuilder path.
The Java version on my MacOS is 1.8.0_261.

Wait for your reply , thanks a lot.

**Comment by ajwfrost** [comment]
@SD216814 when you say the same issues: do you get that same pop-up error message? or is this one of the "failing silently" issues that we also see with FB sometimes?
thanks

**Comment by blackjyn** [comment]
@SD216814 Like I said , setting the JRE to use via `Preferences->installed` JRE **didn't work**

All I did was simply overriding the JRE shipped inside the Flash Builder (that is , version 1.6) with the JRE 8 that comes with the JDK installation.

It just straightforward copy-paste :
![flash builder project explorer err with solved ](https://user-images.githubusercontent.com/6046191/134656330-badd9b12-de03-4c83-89d9-e66f880432c9.png)

**Comment by SD216814** [comment]
> @SD216814 when you say the same issues: do you get that same pop-up error message? or is this one of the "failing silently" issues that we also see with FB sometimes?
> thanks

YES , the same err message. 
Since upgrade airsdk to 33.1.620, occur the same err in the FlashBuilder Package Explorer.
When change air sdk back to 33.1.1.190, all works well.

**Comment by SD216814** [comment]
> @SD216814 Like I said , setting the JRE to use via `Preferences->installed` JRE **didn't work**
> 
> All I did was simply overriding the JRE shipped inside the Flash Builder (that is , version 1.6) with the JRE 8 that comes with the JDK installation.
> 
> It just straightforward copy-paste :
> ![flash builder project explorer err with solved ](https://user-images.githubusercontent.com/6046191/134656330-badd9b12-de03-4c83-89d9-e66f880432c9.png)
> 
> _tldr; I don't know if it worked on Mac or not, if it does please share with us_

thx for reply, but I cannot find the folder in Mac.
![2121](https://user-images.githubusercontent.com/911609/134657142-49be59ef-8d22-4881-85ef-712a5b89733f.png)

**Comment by blackjyn** [comment]
@SD216814 how about setting the specific JRE to run from `eclipse.ini`? That should be inside `eclipse` folder.
Then add 
```
-vm
/path/to/your/Java/JDK/bin
```

This link might help: 
https://stackoverflow.com/a/23174638/5928411
https://stackoverflow.com/questions/24247384/setting-the-jdk-for-eclipse-in-mac

**Comment by SD216814** [comment]
@blackjyn  thx , I've tried copy the " -vm /path" args to the 
" Adobe Flash Builder 4.7/Adobe Flash Builder 4.7/Contents/MacOS/Adobe Flash Builder 4.7.ini "
" Adobe Flash Builder 4.7/Adobe Flash Builder 4.7/Contents/MacOS/Adobe Flash Builder 4.ini "
" Adobe Flash Builder 4.7/eclipse/Eclipse/Contents/MacOS/eclipse.ini "
But, it did not work.... so sad, maybe I should turn to vscode instead of FlashBuilder ?

**Comment by blackjyn** [comment]
@SD216814 well, you should open new issue on this so Harman can hopefully resolve this on Mac.
You can try VSCode or Intellij IDEA too.

**Comment by ajwfrost** [comment]
Our preference would be for people to move away from Flash Builder! As well as the obvious problem with it being out of support and no longer available from Adobe (and we don't have the rights to continue maintaining it ourselves), it also appears to deep-link into the AIR Developer Tool and call things via direct Java API usage rather than running ADT as a command-line tool .. which means it's a bit of a pain to diagnose these sorts of issues and we're never quite sure how it's doing various things..

Just one thought on this though, the Java version being used should ideally be JRE 8 or JRE 11. We're seeing issues with the latest JREs on macOS as they no longer allow the use of sun-internal classes which is how Adobe had implemented the code signing capabilities...

But if anyone had a cunning way to convert the FlashBuilder project files into a VS Code project or similar, it would be really useful!

thanks
