### ISSUE TITLE
I get this error.

### ISSUE THREAD

**Issue by orcuncun** [airsdk/Adobe-Runtime-Support#1208]
It's fine when I don't connect the Phone when packaging with Animate.
But when I connect the phone I get this error.
![Capture](https://user-images.githubusercontent.com/29103010/135072052-a391a2b1-7834-4050-beb4-28b61d626a47.PNG)

**Comment by ajwfrost** [comment]
I assume you've got an option ticked somewhere that's telling it to deploy the packaged application onto connected devices ...

Do you also have a setting in your configuration file that's telling the ADT tool to create an Android App Bundle? as the 'base.apk' thing makes me think it's a bundle that's being generated rather than a normal APK.

thanks

**Comment by orcuncun** [comment]
I'm already trying to package it as .aab and I want to test it on the phone.
That's not possible for now, is it?
I need to test it by downloading it from the store.

**Comment by marchbold** [comment]
aab is a release package for uploading to the store. It is not an installable application.

To generate an installable application from an aab you can use the bundletool or upload to a test channel in the play console and install it through there.

https://airsdk.dev/docs/tutorials/platform/android/packaging-android-app-bundles/#testing

**Comment by ajwfrost** [comment]
To create an APK set from a bundle that's suitable for the phone, and to install this, you can use bundletool in two steps; we've also combined these into a single step so that you can use the ADT -installApp with a bundle type.

I suspect the error that you're seeing above from Animate is if you're overriding the normal Animate build/install of an APK file and using the AIR SDK configuration file to tell it to create a bundle instead .. then, it will likely create a bundle but with an .apk extension, and the AIR -installApp would then treat this as an .apk file.

I guess either we should ignore the request from Animate to create an .apk extension, or we should be inspecting the zip that we get into -installApp so that we can detect if it's a bundle or not rather than just relying on the file extension!
