### ISSUE TITLE
Stage3D problems with M1 Macs after upgrading to 33.1.1.633

### ISSUE THREAD

**Issue by BMGMobile** [airsdk/Adobe-Runtime-Support#1338]
We upgraded our macOS build from Air 32 to Air 33.1.1.633 to fix the Mac Monterey keyboard issues and now we are receiving user reports that our game is now showing up as a black screen for users with M1 chipsets. We use Stage3D for rendering in our game so it's likely that there's a problem in that layer. We first attempt to create a Standard Extended profile, but we'll gracefully fall back to Baseline Extended or Baseline if profiles are unavailable.

**Comment by ajwfrost** [comment]
Just a quick query as to whether you also use HTMLLoader or the non-native StageWebView implementation? As the only issues I know about on M1 are due to the internal WebKit library being only x64 format. So if someone launches an app then it by default will start using the arm64 implementation, and then fail when it hits a request to load the WebKit library.

Otherwise -> are you able to run with Scout to see what might be happening? Or, feel free to send us your app so that we can try it out on an M1-based Monterey machine..

thanks

**Comment by BMGMobile** [comment]
I replied privately with details, but it looks like this is due to using some custom x64 ANEs. Is there currently a way to generate an x64-only executable or otherwise disable arm64, or is the only path forward for M1 macs now is to fully support arm64?

**Comment by BMGMobile** [comment]
Actually stripping the arm64 code from the universal binary fixed the issue for us! I’m going to close this since it’s a non-issue. Thank you for pointing us down the path to understand the problem.

**Comment by BMGMobile** [comment]
If anyone else has this problem, they can follow [these steps](https://eclecticlight.co/2020/07/30/instant-weight-loss-how-to-strip-universal-apps/) to strip the arm64 code from the binary to work around the issue.
