### ISSUE TITLE
Proximity on IOS blocks event processing when enabled

### ISSUE THREAD

**Issue by cowlinb6** [airsdk/Adobe-Runtime-Support#138]
I you have an app that uses Proximity on IOS. When proximity is triggered (i.e. by covering the light sensor) then no events are sent to / processed until the proximity sensor is deactivated. 

ClientID: iPhone9,4
OS string: iPhone OS 13.1.3 iPhone9,4
Flash runtime version: IOS 32,0,0,160
Adobe AIR version: 32.0.0.109

For example if external events to the app trigger page transitions then these all happen once the proximity has been deactivated.

**Comment by ajwfrost** [comment]
We have a fix for this now where the blanking of the screen by a proximity trigger will be treated as if we are being asked to go into the background.

Currently, to be able to react to proximity events, you need an ANE - we are looking at adding this support natively into the sensor package in the future.

With that enabled, the app will then go into 'background mode' when the proximity sensor is covered, so your app will need to have things set up appropriately in order to continue running in the background (e.g. background execution request, UIBackgroundModes, etc: see https://blogs.adobe.com/airodynamics/2012/05/04/air-ios-background-behavior/)

This stopgap solution will be in our next release..
