### ISSUE TITLE
Android: D8 does not support main-dex inputs and outputs when compiling to API level 21 and above

### ISSUE THREAD

**Issue by Oldes** [airsdk/Adobe-Runtime-Support#1387]
I have own Google Play Services ANE, but when I try to pack a game with this ANE using the latest AIRSDK (v686), it fails with this error:
```
dx tool failed:Error: D8 does not support main-dex inputs and outputs when compiling to API level 21 and above
```

Any idea how to solve it? I'm getting the same error even with the older ANE version, which we are currently using, so the error is not exactly related to my ANE.

I have in manifest: `<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30"/>` 
And I'm using `buildToolsVersion "30.0.3"` and Android Studio Arctic Fox with Java 11.

**Comment by Oldes** [comment]
I should probably note, that I'm NOT building Android App Bundle, but the classic APK (I don't know if it is possible to migrate to the new packing method for old games without extensive source modifications :/ )

**Comment by ajwfrost** [comment]
Hi

I think this is due to how the DX tool (which is about to be retired anyway I think!) is handling the multi-dex mechanism where it's splitting the code in your app up into smaller packages. We can take a look but the more future-proof mechanism would be to use the newer toolchain which is what the App Bundle route provides.

But if you're just creating an APK file then we've not updated that yet: you can do it manually though if you set the adt.cfg file to have `KeepAndroidStudioOutput` set to true, and then build for an app bundle target. This will leave you with a folder called `AndroidStudioProject` that you can open within Android Studio: from there, as well as building a bundle, you can just build a normal APK file... (though you may need to do some configuration to only include the native binaries that you want, or to generate two APKs with ARMv7 and ARM64, etc...)

thanks

**Comment by marchbold** [comment]
Please make the apk generation use the same mechanism as aab :) Tough when you are using apk to debug/develop and then it's broken in the aab (or vice-versa).

**Comment by ajwfrost** [comment]
@marchbold yes we'd been planning that for when we did a bit of a major shift in the tools/structure etc along with those config changes that we discussed elsewhere...  but in case it helps, a beta version of that can be found below:
https://transfer.harman.com/message/gbXrnvk8fLTVDk2kIBp6h7

So with this one, as things stand it should switch so that an "apk", "apk-debug", "apk-captive-runtime" build will then use the Android Studio project mechanism and will build the APK via the Gradle plug-in.

If people wanted to revert to the earlier mechanism then the app descriptor should be updated, within the `<android>` tag, to add `<BuildLegacyAPK>true</BuildLegacyAPK>`.

@Oldes this should mean that you can drop this updated adt.jar over the previous one and it will, behind the scenes, switch over to using the newer build tools and resource compilers from the Android SDK. The only thing you will have to do is to provide the Android SDK path, either on the command-line or via the config file (and yes, per the suggestions from @marchbold and others, we'll be moving those sorts of config settings into a simpler per-user mechanism at some point...)


thanks

**Comment by Oldes** [comment]
Ok... it looks, that the issue is, when I include `-platformsdk Path_To_Android_SDK` so build-tools v30.0.3 are used. When I don't specify the platform SDK path and tools from the AIR SDK are used instead, the packaging is passed.

The next step will be, if it works or not, but that is probably different issue.

**Comment by Oldes** [comment]
@marchbold does @distriqt provide working Google's API (licensing, play services) ANE which would be ready for API 30 and newer? I'm really tired of everchanging deprecations and blowing dependencies. It is such a mess!

**Comment by marchbold** [comment]
These are the dependencies our ANEs use:

https://github.com/distriqt/ANE-GooglePlayServices

Licensing is one of the extensions with functionality available :

https://github.com/distriqt/ANE-GooglePlayServices/wiki/Licensing
