### ISSUE TITLE
intellij adb server version 41 doesn't match this client 39 killing

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/Adobe-Runtime-Support#1432]
Hello, I have downloaded the latest AIR SDK as well as the latest Android Studio.
I'm getting the error message `intellij adb server version 41 doesn't match this client 39 killing` while I'm trying to debugging on android device.
I figured out that the adb from android studio is 41 but the adb from the AIR SDK is 39. Could we update this please? Thanks so much!

**Comment by jimmymjing** [comment]
Yea, that's also the first come to my mind, but I got error popup when I'm trying to publishing the debug version of the apk: `ADB Forward 7936`

**Comment by marchbold** [comment]
Ah right, yeah that connection error can happen occasionally normally publishing again resolves that?

**Comment by jimmymjing** [comment]
No. It always fails if I update the adb manually in the AIR SDK.

**Comment by marchbold** [comment]
Weird, haven't had that issue.

**Comment by ajwfrost** [comment]
So the issue here appears to be that the newer release of ADB is outputting the port number when there's a successful connection. It's also outputting the "version doesn't match this client" message when it needs to close down an old server and re-start it. In both cases, from ADB's perspective, it's a successful operation.

But it seems as if IntelliJ is treating any output on the stdout as if it's reporting an error, hence it's then stopping its normal operation.

The output (for each of these) only comes out the first time that you use a particular ADB server version, but if you're swapping back and forth between ADB versions then it would keep on outputting these (and that's what happens if you're deploying via AIR).

Ultimately - it would be good if IntelliJ could not treat these outputs as if they were a failure.

But the workarounds above should be okay. I suspect if we do update the ADB version in the AIR SDK then this issue would go away anyway, so I'll check we can do that...

thanks

**Comment by jimmymjing** [comment]
This issue has been fixed in the AIR_SDK_33.1.1.713.

**Comment by EsqualiburDEV** [comment]
Hello
In the latest AIR version 33.1.1.795
The problem reappeared
