### ISSUE TITLE
Animate IDE. Android Gradle-Based Package needs an Android SDK path to be provided.

### ISSUE THREAD

**Issue by DarkAlchem** [airsdk/Adobe-Runtime-Support#1527]
I recently updated to AIR 33.1.1.713 and I was met with the following error:

![image](https://user-images.githubusercontent.com/6392981/148271068-544f98f5-d542-4b22-8647-e4b181fa3b0a.png)

After searching for an answer, I came here and saw two people with similar issues but I'm not tech-savvy enough to understand their answers. So I have a couple of questions I hope could be answered.

1.) Within the adt.cfg file of this AIR update ( lib > adt.cfg ) is a line 'AndroidPlatformSDK=' that says 'path_to_sdk'. Maybe I'm confused as to what the 'SDK' is as I've been working with **Adobe Animate IDE** for **MAC** on all of my Android App Projects, but I put the link to Animate Folder in the terminal to get the link but I get this prompt which makes me think that Adobe Animate isn't the 'SDK' I'm looking for. If anyone has any leads, I would be most appreciative if you would please post them.

![image](https://user-images.githubusercontent.com/6392981/148273183-664d43f3-0d50-466f-aa3f-001617e81c53.png)

2.) I have seen that the correct syntax for Windows users is "C:/Users/PC-1/AppData/Local/Android/Sdk" using the forward-slash instead of backslashes. But I'm trying to understand why it's not working on Mac. I would think the 'SDK' they are referring to in this case is Animate IDE, but it seems I am incorrect. What would be an 'SDK' in this case? Would iOS use a different 'SDK' also? Just making sure how to solve this in the future as I haven't had an issue with previous builds until this one added the better accessibility options.

![image](https://user-images.githubusercontent.com/6392981/148274922-5a84db8f-d28c-4d24-aba5-1f77273da3e2.png)

**Comment by ajwfrost** [comment]
Hi

The SDKs that are referenced here are the Android SDK (from https://developer.android.com/studio/ - the easiest way to set things up is using Android Studio, although you can also just download the command-line tools and use 'sdkmanager' to download the actual Android SDK), and for iOS it's the simulator SDK that's needed (installed as part of Xcode).

So if you're trying to build an Android app bundle (or using a new AIR SDK which uses the Android plug-in for Gradle in order to build APKs) you'll need the Android SDK and tools in order to do this. The "AndroidPlatformSDK" would need to be set to the path for this Android SDK which may be somewhere like `~/Library/Android/Sdk`

Just a quick note, if you're using quote marks for your path then I don't think you should also escape the space characters. So e.g.
`AndroidPlatformSDK="~/path with spaces/"`
or
`AndroidPlatformSDK=~/path\ with\ spaces/`
would work I believe. Although a lot of this is more about how Java interprets the file, rather than how the actual path in the file system would be formatted..


If you don't want to use the Android SDK for building, then you can revert to the original mechanism by adding into the AIR application descriptor (under the `<android>` section) the flag `<BuildLegacyAPK>true</BuildLegacyAPK>`

thanks

**Comment by DarkAlchem** [comment]
Thank you, I appreciate you getting back to me about this. This is really good information and I believe this helps answers my questions about this.

**Comment by Dinesh1974** [comment]
Hi, I am facing a similar issue when I try to deploy an app using Air for android. I installed latest android studio but when I publish I am getting this error "Android Gradle-based package creation needs an Android SDK path to be provided [-platformsdk]". I tried to edit edit the file in the AIR SDK "lib" folder called "adt.cfg", but still I am getting the same error. I am using an animator and have very little knowledge when it comes to publish for apps. I request if you could show me a step by step approach to resolve this issue, I will be very grateful. Thanks
