### ISSUE TITLE
Rendering engine applies AA when swapping back to LOW quality with rotate

### ISSUE THREAD

**Issue by johnou** [airsdk/Adobe-Runtime-Support#1545]
## Problem Description

I didn't write the original scaling code but from my research, "when you rotate a sprite, it gets automaGically associated bitmap buffers for fast manipulation with the rendering engine." [1] so when zooming out (scaling to 0.5) we set the quality to BEST (smoothing?) and rotated to speed up the render engine, and when scaling back to 1 (zoom in - no zoom) quality was set back to LOW and rotation NaN to remove the smoothing / AA so the pixel art is "crisp" [2]

However after updating to the Harman SDK the zoom feature has never worked, after zooming back in - no zoom the render is still AA (undesired behaviour) I have attached a video recording of how the AA is applied to no zoom in the reproducer.

[1] https://stackoverflow.com/questions/15422231/as3-rotationx-and-rotationy-blur-the-original-image
[2] LOW - Graphics are not anti-aliased, and bitmaps are not smoothed, but runtimes still use mip-mapping.

* Which AIR SDK did you use?
33.1.1.713

* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.
At least Windows Desktop

* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
100%

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.

https://user-images.githubusercontent.com/323497/148681302-c31c5514-9cc9-47e8-aca7-a0d0ebe8c287.mp4

Give us a minimal example:

* As little code as possible. Get to the root of the problem!
* As few dependencies as possible. Did the problem pop up with Feathers? Try to reproduce it with Starling only.
* Remove any ANEs (except if they are vital for the problem).
* Include all necessary files (e.g. textures).

https://github.com/airsdk/Adobe-Runtime-Support/issues/1545#issuecomment-1008291581

```
		public function setScale(scale:Number, pivot : Point = null, loc : Point = null, disableStage3d : Boolean = false ) : void {

			if(!_master || !_master.stage || !_display){
				return;
			}

			if (pivot == null) {
				pivot = new Point(_master.stage.stageWidth / 2, _master.stage.stageHeight / 2);
			}
			if (loc == null) {
				loc = pivot;
			}

			pivot = _display.globalToLocal(pivot);

			_scale = scale;

			if (_scale < 1) {
				_display.stage.quality = _scale == 0.5 ? StageQuality.BEST : _display.stage.quality;
				if (!disableStage3d) {
					// https://stackoverflow.com/questions/15422231/as3-rotationx-and-rotationy-blur-the-original-image
					_display.rotationX = 0;
				}
			} else {
				_display.stage.quality = StageQuality.LOW;
				if (!disableStage3d) {
					_display.rotationX = NaN;
				}
			}

			screenOffsetX = loc.x - pivot.x * scale;
			screenOffsetY = loc.y - pivot.y * scale;

		}
```

## Known Workarounds

Recreating the container sprite and moving all children across.

**Comment by johnou** [comment]
Attaching minimal reproducer which hopefully demonstrates what's happening in the video.

[scalebug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/7835045/scalebug.zip)

**Comment by ajwfrost** [comment]
Interestingly, we can see what you mean with the example even if we don't click on the "Scale 50%" button. So it appears that just changing that rotation value will cause the smoothing to be applied...

Default quality appears to be "high" ... and actually, looking at what's happening, the player is completely ignoring the request for "low" quality. There's a comment:
> Multi-window players only support HIGH and BEST quality settings

FYI there is no difference between setting a rotation to "0.0" and setting it to "NaN"...

I just double-checked the behaviour in an older version of AIR (v17) and this looks the same. Plus if you read back the value of stage.quality after setting it to 'low', it still comes out at 'high'. 

The issue seems to be that when you change the rotation level, the sprite gets cached as a 3D-compatible bitmap for fast scaling, and it doesn't appear possible to undo this.

FWIW, if we change the code to allow a 'low' quality, then the images stay sharp i.e. there is no smoothing, as you would hope. So the only issue here really seems to be either that (a) there's no way to destroy the bitmap created due to the use of a 3D API (rotationX), or (b) the desktop builds of AIR don't allow a medium/low quality level and hence are always applying anti-aliasing and smoothing to bitmaps.

Would be interested in any thoughts on this, my only concern with removing the limit on the quality levels are that could affect other folks' applications, so maybe there could be an opt-in switch in the app descriptor file? I was actually a little surprised to find that that wasn't already a `<quality>` element within the `<initialWindow>` section... but that would be my proposal i.e. if we add that element to the app descriptor, and you set it to medium or low, then this would turn off the limit within the runtime which is pegging apps to a high/best setting at present.

thanks

**Comment by johnou** [comment]
@ajwfrost if there were a way to opt in for this behaviour to maintain backwards compatibility that would be fantastic.

**Comment by johnou** [comment]
@ajwfrost I don't know if this is related or not but it seems OSX doesn't support low quality / no AA when render mode is CPU..

```
# fix blur issue on osx
sed -i.bu 's/<renderMode>cpu/<renderMode>gpu/g' $WORKSPACE/fcf/HabboAir/source/habbo-air-app.xml
```

**Comment by johnou** [comment]
@ajwfrost would you like for me to create a new issue for the problem mentioned above with OSX?

**Comment by johnou** [comment]
[AIR 33.1.1.795] (08-Mar-2022)

Enabling low/medium quality mode on desktop builds via an 'allowLowQuality' tag in the 'initialWindow' section of the application descriptor file.

@ajwfrost thanks!
