### ISSUE TITLE
Android Gradle-Based Package needs an Android SDK path to be provided.

### ISSUE THREAD

**Issue by LOLODEBRIGHTON** [airsdk/Adobe-Runtime-Support#1618]
Impossible to publish .apk and .ipa from ADOBE ANIMATE 2022 using the latest configuration:

Set-up is:

 Adobe Animate 2022
 Mac OS Montery 12.2

Tried Latest AIR SDKs and earlier ones without success...
AIR 33.1.1.743
AIR 33.1.1.758
![error_animate](https://user-images.githubusercontent.com/45128070/152350853-fe79a7d6-0afb-4e78-b665-e1db64c9167e.jpg)

I keep getting that error:

**Android Gradle-Based Package needs an Android SDK path to be provided. [-platfrom sdk]**

Any ideas?
@ajwfrost ?

**Comment by ajwfrost** [comment]
So you have two options here:
1) if you edit your application descriptor file, in the `<android>` section you can add a line `<BuildLegacyAPK>true</BuildLegacyAPK>` which will make it use the older mechanism that doesn't use Gradle. (I am thinking, perhaps we should default to that behaviour if we would otherwise end up in the above situation....)
or
2) download the Android SDK - simplest way of doing this is to install Android Studio and get it to pull down the latest SDK. Then you can set up the path to the SDK within the configuration file (AIR SDK installation folder -> lib/adt.cfg), or if you install it in the default location then the 33.1.1.758 build should find it automatically. Then the build will proceed using Gradle and the same tools as you get with Android Studio.


thanks

**Comment by LOLODEBRIGHTON** [comment]
Thank you very much for your help, much appreciated!

Same issue using method 1 with added line of code.
I will look into ANDROID STUDIO but how will that work when trying to publish an .ipa?

 It looks like the problem is a  **macOS Monterey + latest AIR SDK**  issue. 
The problem doesn't occur on MAC OS BigSur or on Windows a similar setup:

**Adobe Animate 2021 / 2022
Mac OS Monterey 12.2
AIR SDK
AIR 33.1.1.758**

**Comment by LOLODEBRIGHTON** [comment]
*** <android>
     <manifestAdditions><![CDATA[<manifest></manifest>]]></manifestAdditions>
	<BuildLegacyAPK>true</BuildLegacyAPK>	
    </android>

**Comment by LOLODEBRIGHTON** [comment]
<android>
     <manifestAdditions><![CDATA[<manifest></manifest>]]></manifestAdditions>
	<BuildLegacyAPK>true</BuildLegacyAPK>	
    </android>

**Comment by LOLODEBRIGHTON** [comment]
Solution 1 worked to compile .apk on Mac OS Monterey using AIR 33.12.743. thanks @ajwfrost 

**<android>
     <manifestAdditions><![CDATA[<manifest></manifest>]]></manifestAdditions>
	<BuildLegacyAPK>true</BuildLegacyAPK>	
    </android>**
