### ISSUE TITLE
G DATA Security Client detects adl.exe as a virus "Gen:Variant.Graftor.315032 (Engine A)"

### ISSUE THREAD

**Issue by Adolio** [airsdk/Adobe-Runtime-Support#1620]
## Problem Description

`G DATA` anti-virus software is detecting & removing `adl.exe` on `AIR SDK 33.1.1.743` and `AIR SDK 33.1.1.758`. 

However, it does not complain about `AIR SDK 33.1.1.731` and earlier SDKs.

![GDATA AIR SDK 33 1 1 743](https://user-images.githubusercontent.com/1126990/152575931-a4cac584-311f-4f1b-8437-3a779205ae73.PNG)

**Comment by ajwfrost** [comment]
Thanks for the info ... looking at the "Graftor" details, it looks like this is a detection of a 'potentially unwanted' program:
https://malwaretips.com/blogs/gen-variant-adware-graftor-removal/
> Gen:Variant.Adware.Graftor is a heuristic detection designed to generically detect a Potentially Unwanted Program. A potentially unwanted application is a program that contains adware, installs toolbars or has other unclear objectives.

So this may just be because it's not been used enough. Despite us signing them with EV certificates, there are a lot of anti-virus programs that work on reputation...

I just submitted it to VirusTotal: 64 of the anti-virus systems didn't detect anything wrong with it (including G Data!), whereas 1 (Cybereason) has detected `Malicious.3c089c` whatever that means..

Don't know if the link would work for you but in case it does:
https://www.virustotal.com/gui/file/8ad4b704c5f071b13e99e47227e1c7f4a04bbe0907841312fe48848a975de2d7/detection

The file I uploaded there is the same as the one I just checked on our build machine, details are below in case you want to check you have the same file:
```
MD5      ec5cfbb3c089cb50807444c3c293aa29
SHA-1    d115cc5f0dc3b932cba1e0138f729ff78672256c
SHA-256  8ad4b704c5f071b13e99e47227e1c7f4a04bbe0907841312fe48848a975de2d7
```

Thanks

**Comment by Adolio** [comment]
Thanks for the explanations @ajwfrost.

I'm still a bit surprised that G DATA complains only since `AIR SDK 33.1.1.743` but not before this version.
