### ISSUE TITLE
Compiling and installing on MAC - error

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#1629]
Hey guys,
I am trying to deploy our app, on a MAC, running BigSur 11.6.2
"Agenda" is damaged and can't be opened. You should move it to the Bin.
We compiled using -target bundle which resulted in a app.zip file.

Are we not compiling correctly?

**Comment by raresn** [comment]
@ajwfrost do you have any ideas? Thanks!

**Comment by ajwfrost** [comment]
I think there could be two possibilities:

1) Is it an M1 mac i.e. apple (arm) silicon? and does it use HTMLLoader or StageWebView? If so, try opening the .app "Information" settings and get it to launch via Rosetta so that it uses the x64 binaries..

2) Did you code-sign it? You may need to provide the native signing options to the `-target bundle` command, or else sign it afterwards using `adt -sign`, using a Developer ID certificate that's in your key store..

thanks

**Comment by raresn** [comment]
@ajwfrost  thanks for the reply.
I compiled it as .air, and it installed. Still, bundle is what we need.

1. No. Not the case.
2. Sure, how do I do that? (I am not a mac user, and this a bit over my head.)
This is how we now compile
`/Users/teacher/Desktop/AIRSDK/bin/adt -package -storetype pkcs12 -tsa none -keystore androidMarket.p12 -storepass passHere -target bundle Agenda Agenda-Desktop.xml Agenda.swf icons images`

**Comment by ajwfrost** [comment]
So for applications that need to be deployed to macs, (and to fit into Apple's security requirements), you need to have them signed either with "app store" certificates - and deployed via the App Store - or with "developer ID" certificates:
https://developer.apple.com/developer-id/

If you can create and import a developer ID certificate, then you would do something like:
```
/Users/teacher/Desktop/AIRSDK/bin/adt -package -storetype pkcs12 -tsa none -keystore androidMarket.p12 -storepass passHere -target bundle -storetype KeyChainStore -alias "Developer ID Application" Agenda Agenda-Desktop.xml Agenda.swf icons images
```
(i.e. add some extra signing options after the `-target bundle` which provides the Developer ID certificate name from your key store)

See https://github.com/airsdk/Adobe-Runtime-Support/issues/1040#issuecomment-919709012

thanks

**Comment by radubirsan** [comment]
@raresn running this terminal command fixes the issue:
xattr -r -d com.apple.quarantine Agenda.app

**Comment by raresn** [comment]
@ajwfrost I maanged to genrate the cer file,

Now it's a matter of "importing and using it"
I got this from Apple after generating the certificate:
"If you're generating your first Developer ID certificate, the software that you sign it with must be notarized by Apple in order to run on macOS 10.14.5 or later. Learn how to submit your software for notarization"

I clicked on the learn how to submit your software, and it's super complicated.


Is that what we need to do? Or we just need to now "import" this certificate somehow and use it to sign?

**Comment by raresn** [comment]
Thank you, i will follow the steps in that tutorial - maybe i`ll get lucky :)
If the script you are referring to public?

**Comment by raresn** [comment]
![image](https://user-images.githubusercontent.com/1768694/153652025-00598446-f921-483d-b0bb-9a40ee552ce1.png)
![image](https://user-images.githubusercontent.com/1768694/153652053-aa24b4bb-2837-4152-90b4-d56d57602ee4.png)
@ajwfrost i managed to notarize the app, but I keep getting this, although the was built with -target bundle
1)
AIRSDK/bin/adt -package -storytype pkcs12 -tsa none -keystore androidMarket.p12 -storepass *** -target bundle Agenda.app Agenda-Desktop.xml Agenda.swf icons images
2) 
Then i code signed the app like this:
codesign -f -v --options runtime -s "Developer ID Application: Company Name" "Agenda.app"
3)
Then built the dmg by drag and dropping the Agenda.app to the DropDMG app
4)
Then uploaded the dmg to get notarized
xcrun atool --type osx --file Agenda.dmg --primary-bundle-id appIdHere --notarize -app --username usernameHere --asc-provider ASCProviderHere

Any clue while after these things the app doesn't install?
Here is a link to the actual app that i got in the end [](http://fxstudio.no-ip.org/up/f/Agenda_new.app.zip)

Thank you!

**Comment by raresn** [comment]
> @raresn running this terminal command fixes the issue: xattr -r -d com.apple.quarantine Agenda.app

I actually had to use this to take some files from Harman out of quarantine, the naip and the AIR.framework.
So this is something that Harman needs to apply for AIR as well.

**Comment by ajwfrost** [comment]
Hi @raresn 

The files that you're taking out of quarantine - naip etc - are part of the AIR SDK? Yes this is a fairly crucial (and annoying) step that should be done each time you download a new AIR SDK, across the whole SDK to be on the safe side. We're looking at a different deployment mechanism to try to remove this requirement!

I've just seen your other screenshots:
- the one about it downloaded from the internet will always appear, even when notarised. It's saying it's checked for malicious software, which is what you get when you notarize it...
- if you signed it using just that command with the .app file then I'm surprised the notarization worked... as there will be other components that need to be signed as well. This might be why it's then not able to load those and is complaining that AIR isn't there...

Can you sign it using:
```
adt -sign  -storetype KeyChainStore -alias "Developer ID Application" -target bundle Agenda.app Agenda_signed.app
```
I need to dig out that notarization script, but essentially what it did was:
a) zip up the .app file
b) upload the zip to the notarization service (needs a special app username/password)
c) once we get a response, staple the notarization response to the app
Although it might be that this was done for .pkg files rather than .app folders, I'll check..

thanks

**Comment by raresn** [comment]
The adt command did the job.
So the last thing i did was
5)
xcrun stapler staple "the_file_to_notarize"

Asked a friend with MAC to test, and managed to open it :)

Thank you for all the support. 
You rock!!!
