### ISSUE TITLE
Starling Texture.fromCamera() flickering and a part of the picture is missing on Windows

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#1654]
## Problem Description

Starling Texture.fromCamera() flickering and a part of the picture is missing on Windows

* AIR SDK 33.1
* Air for Windows (Intel UHD Graphics)
* link to the [Starling forum](https://forum.starling-framework.org/d/23556-texturefromcamera-flickering-and-a-part-of-the-picture-is-missing-on-windows)

## Steps to Reproduce

```
package com
{
	import flash.media.Camera;
	
	import starling.display.Image;
	import starling.display.Sprite;
	import starling.events.Event;
	import starling.textures.Texture;
	
	public class MyCamera extends Sprite
	{ 
		private var texture:Texture;
		private var image:Image;
		private var camera:Camera;
		
		public function MyCamera()
		{			
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
 
		private function init(e:Event):void
		{
			removeEventListener(Event.ADDED_TO_STAGE, init);
 
			camera = Camera.getCamera();
			texture = Texture.fromCamera(camera, 1, function():void
			{
				image = new Image(texture);
				addChild(image);
			});
		}
	}
}
```

I tried in macOs, iOS, Android, it work, on Linux see [here](https://github.com/airsdk/Adobe-Runtime-Support/issues/1667).
[Daniel Sperl](https://github.com/Gamua/Starling-Framework/issues/1094#issuecomment-1041417022)'s comment

## Known Workarounds

no workaround

**Comment by PrimaryFeather** [comment]
@pol2095 also created [a minimal example](https://github.com/Gamua/Starling-Framework/issues/1094#issuecomment-1043532843) that uses Stage3D directly (thanks a lot!) – and that example worked fine on Windows!

So I had a look at what Starling does differently compared to the minimal sample – and it's the fragment shader!

Starling requires all textures to use "premultiplied alpha", so it multiplies the alpha value into the RGA values of the texel. Here's the AGAL code from Pol2095's sample:

```
"mov ft0 v0",
"tex ft0, ft0, fs0<2d,clamp,linear>",
"mov oc, ft0",
```

What Starling does is adding an additional line:

```
"mov ft0 v0",
"tex ft0, ft0, fs0<2d,clamp,linear>",
"mul ft0.xyz, ft0.xyz, ft0.www", // <--
"mov oc, ft0",
```

And with this line, the camera image disappears. 

As a first attempt to work around this in Starling I thought I could simply remove that line – but it didn't help. That's because, again, Starling expects all pixels with premultiplied alpha, so it sets the blend factors accordingly (normal blending in Starling is `ONE, ONE_MINUS_SOURCE_ALPHA`, not `ONE, ZERO`).

So my workaround in Starling (as described [here](https://forum.starling-framework.org/d/23556-texturefromcamera-flickering-and-a-part-of-the-picture-is-missing-on-windows/7)) is to manually set the alpha value to `1` for video textures. However, I think it would be preferable if camera textures always used `1` for their alpha value in AIR, because that's what one would expect (and as far as I know, that's the case on all platforms but Windows).

What do you think, @ajwfrost? Should I bake this workaround into Starling or would you rather fix this in AIR?

Thanks in advance!! 😄

**Comment by ajwfrost** [comment]
Thanks for the investigations - it looks like this is only a problem when it's using Direct3D 11 rather than 9 ... we can take a look why this is happening, definitely sounds like something that should be fixed on the runtime.

**Comment by PrimaryFeather** [comment]
> it looks like this is only a problem when it's using Direct3D 11 rather than 9 ...

Ah, that would explain why I didn't notice this earlier! I'm sure I tested it on Windows when I wrote the code, but that was before the switch to Direct3D 11.

Thanks a lot for looking into the issue, Andrew!

**Comment by ajwfrost** [comment]
As a quick update ... there is a bit of code setting up the texture for D3D11 for use with video textures, and it's got a lot of surrounding code/comments talking about XRGB, but the texture is being set up with ARGB. If we switch that to XRGB then we get the video displaying properly (the video information comes through with seemingly random alpha values, but then, that's what it says it will provide according to the media description..)

thanks

**Comment by pol2095** [comment]
Thanks @ajwfrost 
and for this [issue](https://github.com/airsdk/Adobe-Runtime-Support/issues/1667)

**Comment by pol2095** [comment]
Thanks, bug fixed in last SDK.

**Comment by PrimaryFeather** [comment]
Awesome! Thanks for the timely fix, @ajwfrost!
