### ISSUE TITLE
[Mac OS] Why is "Flash Player.plugin" deleted?

### ISSUE THREAD

**Issue by norikoji1** [airsdk/Adobe-Runtime-Support#1660]
Hi, I have a quetion（its not a bug）.

It seems that "Flash Player.plugin"has been removed in [AIR SDK 33.1.1.620].
I couldn't find the item in the release notes. 
Why did you remove "Flash Player.plugin"?

■AIR_SDK_33.1.1.575\runtimes\air-captive\mac\Adobe AIR.framework\Versions\1.0\Resources
```
+---cs.lproj
+---de.lproj
+---en.lproj
+---es.lproj
+---Flash Player.plugin           // ★★★
+---fr.lproj
+---it.lproj
+---ja.lproj
+---ko.lproj
+---Licenses
+---nl.lproj
+---pl.lproj
+---pt.lproj
+---ru.lproj
+---sv.lproj
+---tr.lproj
+---WebKit
+---zh_Hans.lproj
\---zh_Hant.lproj
```

■AIR_SDK_33.1.1.620\runtimes\air-captive\mac\Adobe AIR.framework\Versions\1.0\Resources
```
+---cs.lproj
+---de.lproj
+---en.lproj
+---es.lproj
+---fr.lproj
+---it.lproj
+---ja.lproj
+---ko.lproj
+---Licenses
+---nl.lproj
+---pl.lproj
+---pt.lproj
+---ru.lproj
+---sv.lproj
+---tr.lproj
+---WebKit
+---zh_Hans.lproj
\---zh_Hant.lproj
```

Thank you.

**Comment by ajwfrost** [comment]
Mostly we took that away because it was causing extra issues when trying to do code-signing/notarization of AIR applications, and it didn't really add anything. The library in that folder was just a 'placeholder' plug-in, i.e. it showed a little badge saying "Get Flash Player" that you could click on that would take you to Adobe's site for the download of the Flash Player. If you were actually using an AIR app to host HTML that used the Flash Player, then AIR would be loading the Flash Player that was installed on the machine rather than this plug-in stub anyway.

Note that we're also taking away the WebKit library ... as it's only available for x86_64 and not on M1 Apple silicon; so then the HTMLoader/StageWebView functionality would be provided by the operating system's "webview" component and none of these (with the exception of the Windows IE-based/MSHTML one) supports plug-ins...

thanks

**Comment by norikoji1** [comment]
Thank you for your reply.
I understood your explaination.

My predecessor was using "Flash Player.plugin" but I couldn't determine the need.
Your answer helped me understand the need for this plugin.

this issue resolved and closed.
thank you.
