### ISSUE TITLE
AIR License "adt.lic" gets deleted automatically (AIR 33.1.1.758)

### ISSUE THREAD

**Issue by 2jfw** [airsdk/Adobe-Runtime-Support#1728]
We have just realized that the AIR License `adt.lic` file in "lib" folder gets deleted automatically when building our application with AIR 33.1.1.758 on our CI (Jenkins) server.
The compiled EXE with Captive Runtime does then also show the Harman splash screen.
We could literally see the file being deleted from the folder.

@ajwfrost: Can you please check if there are any conditions for this happening?

**Comment by ajwfrost** [comment]
Yes, that happens if it thinks your license has run out (it should be telling you this in the command-line output, though I guess if it's via Jenkins then you may not see that!).

The license file is checked every couple of weeks to ensure it's valid. And the file itself is then changed so that we know when we last checked .. so it's possible that your file isn't being changed (or that changes are being overwritten) which would make our software think that the license isn't valid any more, so it would delete the file and tell you to contact us ...

If you do still have a valid license, then one way to avoid this is to use the developer ID on the command-line, and it will then just ignore the license file and check with our servers each time. For this you can add ` -licenseDevID {nnn} ` to the start of the command line (before even the `-package` command). At least, that's what was meant to work, I've just tried it and am struggling, which may be the formatting .... will have to check this!

Another option would be to have the license file somewhere else on the system that is in a read/write location, and you can then use `-licenseFile path\to\adt.lic` instead..?

thanks

**Comment by ajwfrost** [comment]
Just to confirm, it does work with the `-licenseDevID` format, you just need to have the developer ID added in there - I'd been trying with an ID that wasn't in our online database! So this may be the simplest solution for a CI server...

If you do have a problem even when running `adt -license` manually, then please contact us via the support email.

thanks

**Comment by 2jfw** [comment]
We made an update to latest **AIR SDK 50.2.1** on our CI and now the Harman splash shows up again.
@ajwfrost could you please check, if something changed with the latest AIR version(s)? We were using **AIR SDK 33.1.1.795** previously.
 `-licenseDevID` is still present and passed as command line argument to adt (see https://github.com/airsdk/Adobe-Runtime-Support/issues/1728#issuecomment-1056526130); the value was not changed.
I did check the last build with AIR_33.1.1.795 and the splash does not show up.

**Comment by ajwfrost** [comment]
Hi

This seems a bit odd, I don't think we've changed anything around this .. I just checked manually via ADT from 50.2.1.1 -> 
```
adt -licenseDevID your_dev_id -license
```
and it went off, checked the server and said everything is fine. I don't know whether you could add an ant task for this check to happen immediately before the `package` request so that you're able to see the output?

When you say that the splash screen is showing up again, is this when you're using the output from that package - I believe from the earlier context you were creating a captive "bundle" for Windows? Would you be happy sending us a zip of that bundle, we can check whether we can reproduce it here and then replace elements with debug versions..? (let me know if you need an upload link, as zip files with .exe inside won't get through our email servers..)

thanks

**Comment by 2jfw** [comment]
Thanks Andrew! I will upload two files and send you the link by email with additional information
