### ISSUE TITLE
No implementation found for VideoViewAIR.nativeSetSurfaceSize

### ISSUE THREAD

**Issue by urthling** [airsdk/Adobe-Runtime-Support#1809]
33.1.1.795 Target: 30

6.0.1
Nexus 5X
Crashlytics:
```
Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for void com.adobe.flashruntime.air.VideoViewAIR.nativeSetSurfaceSize(long, int, int) (tried Java_com_adobe_flashruntime_air_VideoViewAIR_nativeSetSurfaceSize and Java_com_adobe_flashruntime_air_VideoViewAIR_nativeSetSurfaceSize__JII)

```

**Comment by ajwfrost** [comment]
Hmm... well the runtime has a function:
```
JNIEXPORT void JNICALL __attribute__ ((visibility ("default")))
Java_com_adobe_flashruntime_air_VideoViewAIR_nativeSetSurfaceSize
```
so if there's an unsatisfied link error, it may be trying to find the function prior to actually loading the library. Do you have a full logcat output there so that we can look at any clues for what may have been loaded (or not) - I'm wondering whether there is a difference in the initialization/callback order (the nativeSetSurfaceSize method would be called within a "surface changed" callback)

How reproducible is this?

thanks

**Comment by urthling** [comment]
Well, there's a surprise a 5x 6.0.1 -- runs without issue on TestLab!

Gosh, sorry for wasting your time on this @ajwfrost .. Closing this -- must have been something odd when they tried.

**Comment by ajwfrost** [comment]
No worries ... not sure what they may have been doing to get to this point but it would be interesting (and fairly crucial) if it was possible to do this in normal operation!
