### ISSUE TITLE
High requestedDisplayResolution messes up pixel art styling and performance

### ISSUE THREAD

**Issue by LilithRainbows** [airsdk/Adobe-Runtime-Support#1816]
**Issue**:
Pixel art content is visually broken (some pixels looks doubled or stretched) and performance degrades considerably when having fractional display scaling (for example 125%) and setting the requestedDisplayResolution option to High.
Changing it to default makes the CPU usage low but makes the image quality much worse (probably because Windows applies a bilinear filter).

**Affected environments and SDK versions**:
ALL

**Known workarounds**:
Do not set the requestedDisplayResolution option to high, but this is not the desired result as scaling will depend on the host system's scaling implementation and the results will be highly variable (and none of them pixel perfect).

**Examples**:
125% screen scaling, standard requestedDisplayResolution, 2.3% CPU usage:
![image](https://user-images.githubusercontent.com/44578053/161401468-e5255caf-7aad-4d5d-bffa-504d18de9617.png)

125% screen scaling, high requestedDisplayResolution, 17.6% CPU usage:
![image](https://user-images.githubusercontent.com/44578053/161401575-04537161-8c05-4d61-a605-9230a42fa651.png)

100% screen scaling, 2.3% CPU usage:
![image](https://user-images.githubusercontent.com/44578053/161401801-cd22050e-1600-4f1f-87c9-7679cb6158e7.png)

**Comment by ajwfrost** [comment]
Hi @LilithRainbows  - can you please confirm what you mean by "visually broken"? The middle of the images above is the one I think you mean is going wrong - and has the higher CPU usage - but to my eye it looks the same as the bottom image, just scaled up slightly..? the top one to me looks a little fuzzy..

What are the display resolutions here btw? and what render mode are you using (wasn't sure if this was using Stage3D or not .. impressive-looking, regardless of how you've done it!)

thanks

**Comment by LilithRainbows** [comment]
Hi, I think I now understand why pixel art doesn't look pixel-perfect with a 125% scale, it's because the dimensions don't have integers in that fractional scale, for example a 250x300px pixel art would become 312.5x375px later to scale, but since fractions are not allowed, that "visual break" of pixel art is generated, by fractional rounding.
But I don't think that it is possible to fix it, the main problem is the great increase in CPU usage generated by setting the requestedDisplayResolution mode to high, so there is no alternative but to use the standard mode and let the operating system itself take care of it to scale it, but as you can see in the first image, a lot of image quality and color is lost.
Why does AIR require so much performance compared to native OS scaling?
My resolution is 1920x1080 and Stage3D is not used.

**Comment by urthling** [comment]
not sure if this might apply to you -- but in your descriptor, within the `initialWindow` tag do you have:

<depthAndStencil>true</depthAndStencil>

**Comment by LilithRainbows** [comment]
@urthling sadly that doesn´t work, here is the cpu usage with the same content.
First is with high requestedDisplayResolution and second is with standard requestedDisplayResolution, cpu usage is ridiculously high for a 2d pixel art content with some animated objects.

![image](https://user-images.githubusercontent.com/44578053/161820420-e788fb03-f3c9-4e67-abab-7156745c21f1.png)

**Comment by urthling** [comment]
mm, interesting..  ur using `direct` mode right?

**Comment by LilithRainbows** [comment]
I tried using direct mode with depthAndStencil but cpu usage is even higher than cpu render 😂

**Comment by urthling** [comment]
mm..  direct should be off loading to the gpu..   using scout, do you see anything that might explain the cpu usage?

**Comment by LilithRainbows** [comment]
No, it seems like air hdpi scaling trigger high cpu usage when there are objects with changing frames.

**Comment by LilithRainbows** [comment]
Everything, i mean scaling the Display with Windows setting (or any other OS):
![image](https://user-images.githubusercontent.com/44578053/161905812-f8f85712-671c-415b-9b2b-29b5d180e05c.png)

**Comment by ajwfrost** [comment]
Hi

I can see what you mean on those zoomed-in images.. I'm not actually sure off the top of my head how the runtime is treating the different cases; it does have the capability to re-sample things when things are stretched, and the high resolution may be making it work 4x as hard or may be adjusting some other anti-aliasing feature.

Can I ask whether you could supply a sample app that we can use to reproduce this here? We can try setting up a quick project to do the same but I'm not certain that we'd get it working hard enough to notice a difference in the CPU usage like this.

And to clarify re "direct" mode: this actually uses the software renderer for normal displaylist content, it's just the final composition that is handled by the GPU. So it's good for if you're using layers such as StageVideo or Stage3D, but otherwise there's not a huge difference between CPU and Direct mode. 

thanks

   Andrew

**Comment by LilithRainbows** [comment]
Hi, the app is called Habbo, I'm not the developer, I'm a user, so I can't create a separate example app.
But if you want (and have time) to take a look you can go to [habbo.com](https://www.habbo.com/) and login with this test account:
Email: ```exampletest@gmail.com``` - Password: ```example1234```
Then click the Download button and when everything is ready select the Classic Client (it is the one that works with the Harman AIR licensed technology)
In case you can't, I understand, so don't worry, thanks.

**Comment by ajwfrost** [comment]
Thanks - have got that, although it's sticking for me at a loading screen (with some entertaining captions to read whilst waiting) .. I'll try again when not on our corporate network at some point!

**Comment by ajwfrost** [comment]
Hi - okay so yes we can reproduce this, but from what we can tell, this is actually to be expected....

If you have a scaling factor set in Windows, then there are two options of how applications handle it:

a) if they're not aware of this setting, then Windows just scales up the overall window size. This is what would happen if you have the 'standard' display resolution setting. At this point, AIR is running with normal rendering and blitting everything to its window, and then the Windows compositor is scaling it (most likely using hardware acceleration). The overal result is that it's fairly quick (or low cpu) but you'll get some blurring perhaps.

b) if the app is aware of the scaling then Windows doesn't do that, and the app (AIR) is left to do the appropriate scaling. In the case of the high resolution support, this means that AIR will render everything with a scale factor of 1.25 i.e. when you've asked for an object that's 100 pixels across, AIR will render this across 125 pixels instead. The additional work - having to calculate the new locations and having to do blending/rasterisation with sub-pixel precision - is going to push up the CPU, but should mean you get a better representation of the overall output. Although this depends on how it's being draw, what quality levels are set, etc, so it's fairly content-dependent whether it will look better than the Windows scaling or not.. I'm wondering if those sprites are drawn via bitmaps which would likely cause more issues with subsequent scaling, rather than vector graphics... 

Hope that helps..! but I'm not sure there's anything we can do for this scenario. The only thing I wondered is whether we could pass on this sort of information to the application so that it could take advantage of it, but that's likely a lot of work for everyone and may not be what Microsoft were intending..

thanks

**Comment by LilithRainbows** [comment]
Hello, thank you very much for the detailed answer, now I understand, so the increase in CPU is mainly caused because unlike Windows scaling, AIR scaling is not done with hardware acceleration.
And yes, they use Bitmaps instead of vectors, considering all this, setting the requestedDisplayResolution to standard seems to be the most suitable option.
This also explains why CPU consumption was so high with screen scaling when Flash Player was still alive. 🤭
