### ISSUE TITLE
Publishing app on apple store from windows?

### ISSUE THREAD

**Issue by hadisn** [airsdk/Adobe-Runtime-Support#1863]
Hi,

I have few games published on Google Play Store, but I using Adobe Animate CC on windows 10 machine, is it possible to publish also on Apple App Store from windows machine? 

If so, can someone explain basic procedure.

Thanks in advance, I appreciate any advice.

**Comment by ajwfrost** [comment]
For iPhone applications, yes you can use a Windows machine for development and packaging, but there are some steps for which you need a macOS machine and Apple developer account.

You basically need to:
- set up a developer account
- create certificates for development and for app store distribution
- create provisioning profiles for your application
- download the certificates and provisioning profiles onto your Windows machine
- use these when you package up your AIR application into an IPA file

It looks like we're missing a tutorial for all this from the https://airsdk.dev website ... hoping for volunteers for someone to write a page on this :-)

thanks

**Comment by hadisn** [comment]
Thank you Andrew, yes, a tutorial would be nice:)
Can you answer me few more questions:

- For what excatly macOS is needed?
- do I need it for every app when publishing it first time?
- do I need it for every update in future or I need it only once, for first time to get that required files?
I am asking because I need to know should I buy mac :)

If I need it only once then I can use someone's pc. I will register developer account these days.

Thank you for info

**Comment by ajwfrost** [comment]
The problem here is that it's a while since I did this! but from what I recall:

* you need to use a mac in order to create a Certificate Signing Request e.g. via the Keychain tool
* you then can use their website to create the actual certificate
* you may need to do this each time the certificate expires..? so, I think for developer certificates that would mean annually

Xcode tends to take care of a lot of this stuff though .. we can then just export a p12 file from the Keychain tool and use that on Windows....

See http://docs.mobilelabsinc.com/GigaFox/GigaFoxDoc/createAppleDevCertificate.html

You may be able to just borrow someone's mac and use it for the CSR - perhaps worth trying that to start with. On Windows the only extra challenge you may find is that we need some internal Java implementation classes to do the IPA code-signing, and from Java 17 these are no longer accessible. So if you can stick with Java 11 it should be okay..

The other thing to consider is that you will need to have an Assets.car file which holds your application icons etc. This is something you may be able to generate online though.

thanks

**Comment by FliplineStudios** [comment]
We do all of our development on Windows, but like @ajwfrost said we do need a Mac for setting up new Certificates every year, and we use it for creating Assets.car and the launch screen Storyboard for each app.  And every app submission and app update to the App Store needs to be uploaded from a Mac using their tools as well, even though you can generate the final ipa from Windows they won't let you submit it from a Windows PC...

**Comment by PhilCase** [comment]
This website walks you through creating a P12 file from a Windows PC.

https://raaviblog.com/use-openssl-to-create-p12-certificate-in-windows-for-ios-push-notification-or-distribution/

You will have to interact with the Apple Developer Portal to get some of the files you need.

This one has essentially the same information too but the formatting has gone a little strange.

https://www.joshmorony.com/how-to-create-an-ios-provisioning-profile-and-p12-with-windows/

**Comment by koreaflash** [comment]
If you look at the link below, it seems that there is a possible way in MS-Windows as well.
https://takamii.hatenablog.com/entry/2020/12/26/140340

**Comment by hadisn** [comment]
I got some older mac for free :) and i created csr, downloaded provisioning profile, created .ipa file. looking forward to test or upload somehow :)

**Comment by hadisn** [comment]
I am trying to package ipa file with adt because I need to encrypt swf first (with adobe animate i was able to compile .ipa file), but I getting this error with adt: 

Cannot sign an ipa file on non-mac platform: invalid jre that does not expose sun.security classes

**Comment by hadisn** [comment]
For me, it's mission impossible, every step new error. This is too much for me....
![image](https://user-images.githubusercontent.com/2553775/168925194-00823f8b-64db-4a81-85f9-2d7eebdd3da8.png)

**Comment by FliplineStudios** [comment]
Are you sure you generated your p12 correctly that's used for signing?  How did you end up making your p12, did you generate it with Keychain Access on a Mac, or did you create it on Windows?

One way to test on your own iOS device before uploading a release to Apple is to also make an ad-hoc build, since those will use the same p12 distribution cert that App Store releases use.  If you've set up an ad-hoc provisioning profile that will work on your specific device, you can try installing the ad-hoc build on that device to see if it will work or not (and if it doesn't install or just has a grayed-out icon, something is likely wrong with the p12).

**Comment by ajwfrost** [comment]
@hadisn I got a notification of a query that I can't actually see in the above thread, but in case it helps: if you have a problem with code signing errors when using Windows, you would need to downgrade the Java version that you're using. Java 17 has removed access to the internal classes that ADT uses to generate the IPA code signatures; if you use Java 11 it would work.

But yes, getting the right signing certificates and provisioning profile is a bit of a pain...

**Comment by hadisn** [comment]
> Are you sure you generated your p12 correctly that's used for signing? How did you end up making your p12, did you generate it with Keychain Access on a Mac, or did you create it on Windows?
> 
> One way to test on your own iOS device before uploading a release to Apple is to also make an ad-hoc build, since those will use the same p12 distribution cert that App Store releases use. If you've set up an ad-hoc provisioning profile that will work on your specific device, you can try installing the ad-hoc build on that device to see if it will work or not (and if it doesn't install or just has a grayed-out icon, something is likely wrong with the p12).

Thank you for point me to the right direction, i was not generated p12 on Mac, after did that I have another error :D:

Missing app icon 120x120 and 1024x1024

**Comment by hadisn** [comment]
That's it :) Thank you all. 
![image](https://user-images.githubusercontent.com/2553775/170014231-a0e16291-3bab-4a0a-834e-cc39c12e79c4.png)
