### ISSUE TITLE
Failed to install AAB - Pushing additional splits for local testing failed

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#1896]
Failed to install Agenda.aab:
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Pushing additional splits for local testing failed. Your app might still have been installed correctly, but you won't be able to test dynamic modCaused by: java.io.IOException: ADB command failed.
Hey @ajwfrost - i have no idea why we suddently got this. Even tried to upgrade to 821 but still get the same error when trying to install.

Compile doesn't fail, we only get the usual:
Warning: packagedDependency okio-1.15.0.jar used by more than one ANE. Ignoring this entry
NOTE: Multiple Android build-tools folders exist, choosing the latest version (31.0.0) for packaging

**Comment by raresn** [comment]
@ajwfrost any clue what we can do here?

**Comment by ajwfrost** [comment]
Hi

This appears to be a restriction caused by Android itself. I believe the application will actually have installed (per the message) but it may not be possible to test things like the Play Asset Delivery functionality.

See e.g. https://github.com/google/bundletool/issues/196

If you're able to try installing the AAB (via APKS) manually with bundletool, see if it works if you don't have the "--local-testing" option set. We add this by default in ADT because it's needed for the Play Asset Delivery testing, but we didn't have it initially...

thanks
