### ISSUE TITLE
ANR on  using 33.1.1.795

### ISSUE THREAD

**Issue by Gokulv617** [airsdk/Adobe-Runtime-Support#1947]
Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 10. Wait queue head age: 5667.2ms.)

This ANR occurs  in my application.
I am using 33.1.1.795

**Comment by ajwfrost** [comment]
Is this something you're seeing on a device in your possession? I would really like to see a Scout log for one of these.... failing that, do you have any logcat information, call stack etc? There are potentially a number of different causes of ANRs so it would be good to know if this is happening at start-up or whether it's something later on after a long time of running, etc..

thanks

**Comment by Gokulv617** [comment]
Hai I am not holding any logcat I have received anr comments from players and datas from play console

Here is some stack trace

![image](https://user-images.githubusercontent.com/43432782/171173382-8e97d3c2-04fa-4eaf-936a-505099c8796f.png)

**Comment by ajwfrost** [comment]
Hi -> just checking whether you had a call stack or anything available for this?
I think though, it's most likely that some of our existing/ongoing activities should improve these sorts of problems...

**Comment by httpwebmedia** [comment]
Seriously, when will this end? We got that issue for ages now on Android. Latest version I use (.795) gives me 2.95% of ANR....
Is this something you guys really try to deal with?

**Comment by ajwfrost** [comment]
Yes although there are a number of challenges, in particular
- there are a lot of different causes of ANRs .. we've pretty much eliminated the audio-related ones as far as we're aware now
- we've not seen any evidence of further deadlock conditions which means that these ANRs are all purely caused by slow-running or unresponsive code, in a "busy live" condition i.e. it's doing things, and it should complete, but it's being slow
- to eliminate the possibility of ANRs - whilst allowing the app to still be slow - requires an architectural shift. In fact, the majority of the changes we want to make to try to resolve these ANRs will involve re-architecture. And that is (a) difficult and (b) risky, hence it's taking a while.

The interesting thing is that a lot of people don't have problems with ANRs now.. so it seems that there are some particular mechanisms that some folk use which area causing this slow-running/delay thing which makes Android trigger the ANR abort. We just don't know what those are, and haven't got any way of reproducing these ANRs on any test devices..

Things that would help:
1) call stacks: that's how we identified and fixed the audio-related problems, as the ANR call stack showed we were waiting for a mutex i.e. a thread was deadlocked. A lot of the call stacks we've seen suggest that a significant number of problems occur during start-up so we're trying to improve that time
2) Scout logs for long-running scenarios: the one operation I know can take a bit of time is the "sweep" part of garbage collection, and if we could any Scout logs that showed GC taking a bit longer than we'd expect - and perhaps a duration that then increases over time - it could indicate some optimisations either in the app itself or in the memory management/object re-use etc. But Scout would also show if there are other frames that are glitching, which may indicate other problems.

Summary: we're working on a number of approaches here, as outlined in some other discussion items, but I'm afraid it's taking more time than we'd hope.
