### ISSUE TITLE
How to add a provisioning profile to a Mac app?

### ISSUE THREAD

**Issue by yrozijn** [airsdk/Adobe-Runtime-Support#2037]
Is there a way to add a provisioning profile when building a Mac app?
The command `adt -package -target bundle ...` for building a Mac app doesn't like the `-provisioning-profile` parameter.
Does anybody know if there is a way to add a provisioning profile manually to the app?
Or does this require a change to adt?

**Comment by ajwfrost** [comment]
Hi

Does it work if you just include the provisioning profile along with the rest of the contents, alongside your main SWF file? it's meant to be called "embedded.provisionprofile".

For iOS we'd got this as a specific argument because we inspect it for things like iPhone/iPad compatibility, developer vs production distribution rights, etc, and it then affects the code signing. So there may be a possibility we have to do this for mac as they seem to be introducing some requirements here, but our current understanding is that the entitlements from the code-signing, plus things like the certificate details and app ID, will need to match the information found in the provisioning profile (which itself is of course signed as part of code-signing) - so there's no actual special handling for this file currently.

Reference: 
https://developer.apple.com/documentation/technotes/tn3125-inside-code-signing-provisioning-profiles#Entitlements-on-macOS

thanks

**Comment by yrozijn** [comment]
Thanks, that link didn't show up in my search results.
I'll try and include the provisioning file as you suggest.

**Comment by yrozijn** [comment]
If I include embedded.provisionprofile alongside the main SWF file, it ends up in MyApp.app/Contents/Resources. But I can copy it manually to MyApp.app/Contents (and re-sign everything) and then it seems to be accepted fine. Thanks again.
