### ISSUE TITLE
ADOBE AIR FPS 32 PIX

### ISSUE THREAD

**Issue by SEMOKISOFT** [airsdk/Adobe-Runtime-Support#2066]
https://github.com/airsdk/Adobe-Runtime-Support/issues/307

If I make a normal SWF in ANIMATE, it runs well at 60 frames in a file with nothing.

However, when changing to AIR, even in a new project with nothing, the frame does not rise above 32.

I have checked several times that there are 2-3 issues and bug reports on this issue, but there has been no 

further answer for a year and it is still like this.

**Comment by ajwfrost** [comment]
Hi

I think we'd found that in real-world cases, rather than when debugging within Animate/ADL, then this issue isn't really such an issue. We did go some way into reworking the whole frame/playback loop but whatever option we tried it ended up with some drawbacks and some conditions at which the nominal frame rate would drop...

Trying the old "hello triangle" Stage3D test case here and we hit 60fps after it settles down, so it's likely to be some combination of settings/content that's causing the slowdown that you're seeing.

thanks

**Comment by SEMOKISOFT** [comment]
Thank you very much for your valuable reply I always read it with your eyes I am always grateful for your hard work I have confirmed that this part comes back to normal when I test it with the scout turned on as I mentioned before. I really love AS3
I sincerely hope that you will continue to win and win with Haman. Thank you.
