### ISSUE TITLE
Device Rotation iOS 16 not working

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#2257]
Before reporting this issue:

- you should consider whether this would be a question better suited to discussions above ^^ ;
- make sure you have searched for similar issues and add your experience there if one exists.

## Problem Description

Rotation on iPhone not working correctly since iOS 16. Moving from a Landscape Screen to a Portrait Screen does not work. The Screen appears in the correct layout, but the app itself is still in landscape. Bottom bar stays at the left side of the phone when in portrait position and not at the bottom. 
iPad  rotation does not work too. If set to Landscape the iPad rotates also to Portrait. Even when setting stage.autoOrients = false the iPad rotates to portrait.
Downloaded the ANE from case #2170. Worked on the simulators, but could not test it because of compilation error.
Compilation failed while executing : ld64
Packaging output:
Undefined symbols for architecture arm64:
"_objc_msgSend$keyWindow", referenced from:
_SetAspectRatio in libcom.harman.AIRiOSAspectRatioHandler.a(iOSAspectRatioHandler.o)
"_objc_msgSend$rootViewController", referenced from:
_SetAspectRatio in libcom.harman.AIRiOSAspectRatioHandler.a(iOSAspectRatioHandler.o)
"_objc_msgSend$sharedApplication", referenced from:
_SetAspectRatio in libcom.harman.AIRiOSAspectRatioHandler.a(iOSAspectRatioHandler.o)
"_objc_msgSend$setNeedsUpdateOfSupportedInterfaceOrientations", referenced from:
_SetAspectRatio in libcom.harman.AIRiOSAspectRatioHandler.a(iOSAspectRatioHandler.o)
ld: symbol(s) not found for architecture arm64

* Which AIR SDK did you use? 50.0.1.1
* Describe the affected environment: iOS 16 
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)? #2170

Could you please add the missing symbols to the ANE for architecture arm64 to test the temporary fix on a device?
Thank you!

**Comment by gsynuh** [comment]
Hi @apofis1969,

I'd like to know if you solved the device orientation issue itself, 

I know moving to the 50.1 sdk makes the ANE use obsolete, see issue 280 with my comment where I describe a solution involving a distriqt ane
https://github.com/airsdk/Adobe-Runtime-Support/issues/280#issuecomment-1377315028

But I'm really curious to know where you are at, since I'm interested in having the stage oriented in a specific way and for the keyboard to pop in that way as well (see home bar not being in the right place as  you mention)

Thank you for any extra information you could provide
I'm trying to gather as much info as possible

**Comment by gsynuh** [comment]
@apofis1969 Oh I see, so you designed around the problem. I can't afford that but thank you for your reply !

**Comment by gsynuh** [comment]
@apofis1969 Sorry, I meant you seem to have found a way that relies on the user doing the right thing and rotating the device the right way (by telling them to do so), 

and when they do that the ios view (I'm taking the home bar for reference) moves to the right place and everything works from there right? for example the keyboard pops up in the right direction even though the device is oriented in landscape?

If I understood that correctly, then what I can't afford is expecting the user to do the right thing and have an extra screen, I'd like the same behaviour as on android which is that stage.stageAspectRatio/setOrientation changes the os's view properly because my portrait view can't exist in landscape (not designed to work in different orientations) as are my landscape views.

Hope it makes sense 😞

**Comment by MalacTheLittle** [comment]
Please check my problem solution, maybe it helps you:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2170#issuecomment-1381793796
