### ISSUE TITLE
Reg:iPhone13 bug

### ISSUE THREAD

**Issue by Gokulv617** [airsdk/Adobe-Runtime-Support#2278]
Full screen not appears in iphone 13 i am using 33.1.1.795 and 33.1.1.935 and what to do now.I am a subscription member of airsdk i have purchased professional tier ...i am using those license.

I am using these default images.
1136*640 and 640*1136 what size i will use for iphone 13

If i am using 33.1.1.713 i am getting full screen but if i use licnese means full screen not appear

**Comment by ajwfrost** [comment]
Have you got your own launch screen that you're adding? We had a situation recently where an app wasn't using the whole of the screen (had black bands above/below) when it was using a custom launch screen, but if the license file was removed and our default (Harman/AIR logos) launch screen was injected, then the app displayed properly as full screen. So it may be the set-up of the launch screen?

**Comment by Gokulv617** [comment]
Yes But i need the app with license only,what to do now,If i add license means full screen not appear

**Comment by ajwfrost** [comment]
Have we got two issues the same here? .. just commented on the above picture under #2262 ..

So yes, on iPhone 6 I guess it wouldn't need the launch screen, but you'd need to have a launch screen now in order to set up the resolutions.. our 'default' Harman/AIR launch screen would be injected if you don't have a license; if you do have a license then you'll need to add your own launch screen. Do you have a mac, and if so can you create a launch screen/storyboard and add this to the project files?

**Comment by Gokulv617** [comment]
Yes I have mac  but what is the procedure to create a launch screen

**Comment by Gokulv617** [comment]
Ok I will try.

**Comment by marchbold** [comment]
Also a useful script here: 

https://github.com/distriqt/AIR-ImageScripts
