### ISSUE TITLE
[TextField].getCharIndexAtPoint return wrong value when .scrollH > 0

### ISSUE THREAD

**Issue by ylazy** [airsdk/Adobe-Runtime-Support#2315]
```as
var tf:TextField = new TextField();
tf.wordWrap = false;
tf.width = 200;
tf.height = 30;
tf.text = "the quick brown dog jumps over a lazy fox then the lazy fox jumps over the brown dog";
trace(tf.getCharIndexAtPoint(100, 5)); // 19 (correct)
tf.scrollH = 50;
trace(tf.getCharIndexAtPoint(100, 5)); // 19 (incorrect. The result must be greater than 19 because the text field is horizontally scrolled)
```

This also results another issue: **There's no way** to get the character index under the mouse if the text field is horizontally scrolled.

**Comment by manishpatel0404** [comment]
Maybe you can try this:

`trace(tf.getCharIndexAtPoint(tf.scrollH + 100, 5));`

This way, if the text is not scrolled, scrollH would be 0 and the above would still work.

**Comment by ylazy** [comment]
@manishpatel0404 your solution doesn't work in all cases. For example:
```
trace(tf.getCharIndexAtPoint(180, 5)); // 35
tf.scrollH = 50;
trace(tf.getCharIndexAtPoint(180+50, 5)); // -1
```
because 180+50 > 200

**Comment by manishpatel0404** [comment]
Yes. I was hasty.

There is an ugly way to get around this, using the code below:

`var tf:TextField = new TextField();
tf.wordWrap = false;
tf.width = 200;
tf.height = 30;
tf.text = "the quick brown dog jumps over a lazy fox then the lazy fox jumps over the brown dog";`

**Comment by manishpatel0404** [comment]
Yes, I was a bit hasty.

There is an ugly way around this by using a second `TextField` having the full width of the text.

`var tf:TextField = new TextField();`
`tf.wordWrap = false;`
`tf.width = 200;`
`tf.height = 30;`
`tf.text = "the quick brown dog jumps over a lazy fox then the lazy fox jumps over the brown dog";`

`var tf2:TextField = new TextField();`
`tf2.width = tf.textWidth + 4; // TextField adds a 2-pixel gutter at each end of the text when displaying text.`
`tf2.height = 30;`
`tf2.text = tf.text; // I believe, this should also work with tf2.htmlText = tf.htmlText` 

`tf.scrollH = 50;`
`var tf2CharIndex:int = tf2.getCharIndexAtPoint(180 + tf.scrollH, 5); // (tf.mouseX instead of a static horizontal value).`
`trace(tf2.getCharIndexAtPoint(tf2CharIndex, 5));`

**Comment by ylazy** [comment]
Thank you @manishpatel0404 
Actually I ran into this bug years ago, when Harman hasn't pick up the Air yet. At that time, I known that Adobe doesn't take care about bugs and I even haven't report it to Adobe. I did all I could to resolve this issue but there's nothing work without paying a big price. Your solution work, but it result another issue: performance issue. Everything will be **duplicated**. TextField is already the slowest display object. Duplicating the text will make it x2 slow. Especially when you have a TextField with large htmlText and format, contains link events...

I guess it won't take much time for Harman to fix this, maybe several lines of code. It would be better any workaround we can think about. ;-)

**Comment by ajwfrost** [comment]
Hi

I like this part:
> I guess it won't take much time for Harman to fix this

Expanding the test a little given your other case earlier:
```
			var chIdx : int = tf.getCharIndexAtPoint(110, 5);
			trace("Unscrolled, point 110: " + chIdx + " = " + tf.text.charAt(chIdx));
			chIdx = tf.getCharIndexAtPoint(180, 5);
			trace("Unscrolled, point 180: " + chIdx + " = " + tf.text.charAt(chIdx));
			tf.scrollH = 50;
			chIdx = tf.getCharIndexAtPoint(110, 5);
			trace("Scrolled, point 110: " + chIdx + " = " + tf.text.charAt(chIdx));
			chIdx = tf.getCharIndexAtPoint(180, 5);
			trace("Scrolled, point 180: " + chIdx + " = " + tf.text.charAt(chIdx));
```
We also checked vertical scrolling but that's already accommodated it seems.

But yes, a fairly quick fix, one line but it has to be in the right place otherwise the character under (180,5) has the same issue you find when using this externally.

Results from the current runtime:
```
Unscrolled, point 110: 21 = u
Unscrolled, point 180: 35 = z
Scrolled, point 110: 80 =  
Scrolled, point 180: 95 = a
```
Results from our fixed build:
```
Unscrolled, point 110: 21 = u
Unscrolled, point 180: 35 = z
Scrolled, point 110: 31 = a
Scrolled, point 180: 45 = n
```

Will get this into a release soon..
thanks

**Comment by ylazy** [comment]
@ajwfrost Fantastic!
Thanks!!!
