### ISSUE TITLE
50.2.1.1 Mac debug launch from IntelliJ not working, captive runtime build also broken

### ISSUE THREAD

**Issue by kasparv** [airsdk/Adobe-Runtime-Support#2512]
Updated Mac SDK to version 50.2.1.1

Debug launch from IntelliJ is now broken with the following error:

`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`

Also, captive runtime build now givers the following error: 

```
ERROR: the AIR SDK should have symbolic links within the 'Adobe AIR.framework' folders
Please check that the SDK was correctly extracted to ensure MacOS App Bundles are correctly formed.
SDK is missing file apache-flex-sdk-4.16.1-air-50.2.1.1/runtimes/air-captive/mac/Adobe AIR.framework/Adobe AIR
```
The supposedly missing file is actually present in that location and showing 33,1 MB in size.

iOS Build however ran fine with the new SDK and also the built iOS app was performing fine.

Known fix: Use `cp -Rf` command to overlay Flex SDK

**Comment by ajwfrost** [comment]
Ah, so that error message is something we added in to avoid later problems that macOS would throw at you due to a malformed framework. It sounds like the AIR SDK installation hasn't copied the folder structure properly: that "Adobe AIR" file that you say is 33.1MB should actually just be a symbolic link, and having it as the real file will destroy the code signature (which I suspect is why the process is killed when you try to launch it).

Can I check, how did you merge the AIR SDK over the top of the Flex SDK? Plus, how did you get the AIR SDK in the first place - was it via the SDK Manager, or by downloading the large zip file? We can check these components to make sure they're set up right, but it may also have been how you merge one SDK with another where copying needs to preserve symbolic links...

thanks

**Comment by kasparv** [comment]
I did overlay the Flex SDK with the contents of this zip download
`https://airsdk.harman.com/api/versions/50.2.1.1/sdks/AIRSDK_Flex_MacOS.zip?id=86989`
Ran the quarantine command as usual and I am getting the results described above.
When I do the same with the older SDK
`https://airsdk.harman.com/api/versions/50.1.1.2/sdks/AIRSDK_Flex_MacOS.zip?id=70478`
everything is working fine...

**Comment by kasparv** [comment]
@ajwfrost Update: I created the SDK on another Mac and the debug launch from IntelliJ works there, the captive runtime build issue however still exists.

**Comment by ajwfrost** [comment]
Curious then, it seems to be okay when I download that .zip file and check it (expanded automatically by macOS).

Ah .. I suspect the culprit is this:
```
cp -rf AIRSDK_Flex_MacOS/* apache-flex-sdk-4.16.1-bin
```
since if I do something similar:
```
cp -rf runtimes/air/mac testcp
```
and then
```
% ls -la testcp/Adobe\ AIR.framework
total 70032
70032 -rwxr-xr-x@  1 andrewfrost  staff  35853808 Mar  7 17:43 Adobe AIR
    0 drwxr-xr-x@  4 andrewfrost  staff       128 Mar  7 17:43 Headers
    0 drwxr-xr-x@ 25 andrewfrost  staff       800 Mar  7 17:43 Resources
    0 drwxr-xr-x@  4 andrewfrost  staff       128 Mar  7 17:43 Versions
```
I've lost the links... but if I do:
```
cp -Rf runtimes/air/mac testcp
```
then:
```
% ls -la testcp/Adobe\ AIR.framework
total 0
drwxr-xr-x@ 6 andrewfrost  staff  192 Mar  7 17:45 .
drwxr-xr-x@ 3 andrewfrost  staff   96 Mar  7 17:45 ..
lrwxr-xr-x  1 andrewfrost  staff   26 Mar  7 17:45 Adobe AIR -> Versions/Current/Adobe AIR
lrwxr-xr-x  1 andrewfrost  staff   24 Mar  7 17:45 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 andrewfrost  staff   26 Mar  7 17:45 Resources -> Versions/Current/Resources
drwxr-xr-x@ 4 andrewfrost  staff  128 Mar  7 17:45 Versions
```

Are you able to try your copy command again but with a capital 'R'?

thanks

**Comment by kasparv** [comment]
@ajwfrost Yes, that was it! Thank you! 
Perhaps it's time to update the readme part for overlaying Flex SDK that links to old Adobe instructions?

**Comment by ajwfrost** [comment]
Great, thanks for confirming.
Yes, good idea, I think when we first did that readme we weren't really sure exactly the details and pitfalls in quite the same way! The end goal is to add this capability to the AIR SDK Manager though which should make it a lot easier!

thanks
