### ISSUE TITLE
Can not build Windows Bundle anymore on Windows 11

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#2550]
I am using Parallels Desktop with Windows 11 to build the Windows EXE file.
I added Windows_AIRSDK 50.2.1.1
I build the bundle this way, which worked until today after Windows 11 did an update:
C:\Users\user\sdk50-2-1-1\bin>adt -package -keystore cert.p12 -storetype pkcs12 -storepass xxxxx —target bundle MyApp MyApp-app.xml -extdir lib MyApp.swf AppIcons
I get the error message at the command prompt: **no such file C:\Users\user\sdk-50-2-1-1\bin\MyApp**

How to resolve this? I installed on my other mac a demo version of the Windows 11 on Parallels and did not any update. There the bundle is created with the same adt command line correctly.

**Comment by ajwfrost** [comment]
A "no such file" error implies that it's had a problem parsing the command line, and is thinking that "MyApp" is meant to be an input file rather than an output file. Looking at the command line, if you just copied/pasted, is that a long dash or a double-dash before `target`? (copying/pasting here, I see `—target` vs `-target` - the different character code may be confusing it?)

Otherwise - if you can check the adt.log file (or use the AIR SDK Manager's "troubleshooting" tab) we can see what it's thinking internally..

thanks

**Comment by apofis1969** [comment]
Hi @ajwfrost, thank you. was the dash. Don't know how it happened and sorry to incommode you with this problem.
