### ISSUE TITLE
Proper TCP_NODELAY support

### ISSUE THREAD

**Issue by henke37** [airsdk/Adobe-Runtime-Support#2569]
The current implementation of this feature is a hack.

The hack should be retired and replaced with a proper API update.

Add a property to the `flash.net.Socket` class to control this feature.

**Comment by ajwfrost** [comment]
Yes, absolutely, the functionality was added via a configuration that is a hack so that the capability could be provided urgently to a customer.

An AS3 API update is going to happen but we are trying to ensure these are properly version-controlled i.e. when the API changes, the SWF version changes, and the major revision number changes, and there are a lot more steps to go through and other changes to make in order to get that working properly.

When AIR 51 comes out, it will have an API for this as you're suggesting..

thanks

**Comment by henke37** [comment]
Looks like this is implemented and due to be released any day now.
