### ISSUE TITLE
What parameters can be set for packaging APK with Air SDK use the aapt2 instead of aapt ，the ANE needs to use aapt2.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#2624]
Hi,
What parameters can be set for packaging APK with Air SDK use the aapt2 instead of aapt ，the ANE needs to use aapt2.

**Comment by ajwfrost** [comment]
To use aapt2 you need to have the 'gradle' build mechanism. If you run ADT with logging you can find out the reason why it may not do this, but the basic requirements are:
a) namespace of 33.1 or later
b) JDK 1.8 (or later) available
c) 'BuildLegacyAPK' setting to false (or omitted)

If those conditions are all met, you should see from the log that it's using Gradle to build. The legacy mechanism uses aapt and the dx/d8 compilers manually..

**Comment by pengyangjin** [comment]
I use -platformsdk to set Android Sdk path , is there have parameter to set JAVA_HOME only used for adt? because I need use JDK 8 for other things,can not be set JAVE_HOME in system environment variable.


<arg value="-platformsdk"/&gt;
<arg value="D:/application/Android/Sdk"/&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] What parameters can be set for packaging APK with Air SDK use the aapt2 instead of aapt ，the ANE needs to use aapt2. (Issue #2624)





 
To use aapt2 you need to have the 'gradle' build mechanism. If you run ADT with logging you can find out the reason why it may not do this, but the basic requirements are:
 a) namespace of 33.1 or later
 b) JDK 1.8 (or later) available
 c) 'BuildLegacyAPK' setting to false (or omitted)
 
If those conditions are all met, you should see from the log that it's using Gradle to build. The legacy mechanism uses aapt and the dx/d8 compilers manually..

**Comment by ajwfrost** [comment]
You can set it in the ADT configuration file (c:\users\username\.airsdk\adt.cfg) or if you're using the AIR SDK Manager, there's a configuration setting for it there.. There's no command-line option for it though.

**Comment by kidsacademyteam** [comment]
Besides 'gradle' build mechanism requirements (see post 2) you must add <createAppBundle></createAppBundle> to project manifest under <android> section and set it to:
false, if you need apk
true, if you need aab.

Keep in mind that aab build still can have .apk extension :)

**Comment by pengyangjin** [comment]
> Besides 'gradle' build mechanism requirements (see post 2) you must add to project manifest under section and set it to: false, if you need apk true, if you need aab.
> 
> Keep in mind that aab build still can have .apk extension :)

Could you explain it in more detail? I don't quite understand what you're say "Keep in mind that aab build still can have .apk extension".

**Comment by marchbold** [comment]
@pengyangjin He's talking about the `createAppBundle` flag either in your adt.cfg fiile or in the [app descriptor](https://airsdk.dev/docs/building/application-descriptor-files/elements/android#createappbundle). This flag forces the output to be an `AAB` even if the command specifies an `APK` output. So you may end up with a file that has the `apk` extension but is actually an `aab`. This is mainly a workaround for getting an `AAB` from tools like Animate that don't have the ability to specify that output. 

However you don't have to add this to use the gradle build method!

**Comment by marchbold** [comment]
@ajwfrost Is the Android SDK also required for the gradle build method? Or have I been wrongly assuming that?

**Comment by ajwfrost** [comment]
Yes, you need to have an Android SDK installed, as it uses this for the build tools, platform libraries etc.
We've tried to get it set up so that if you have Android Studio installed and functioning normally - i.e. it's got reasonably recent Android build tools, SDK etc - then we will find what's needed from there:
- Android Studio includes a JDK that will (I assume) always be appropriate for running Gradle
- It downloads the Android SDK to a user-specific location

But equally you can set these values in the adt.cfg file or via the AIR SDK Manager.

Then if you have your app descriptor namespace at 33.1 or later, and you don't have the `BuildLegacyAPK` value set to `true` in your app descriptor, we should use Gradle (and hence aapt2 and the latest Android compilers) for both APK and AAB builds.

As above, you can force output to AAB if you use `createAppBundle` which is needed if you're publishing to the Play Store but using an IDE like Animate which calls our ADT tool but will always specify to create an APK file with a filename ending in .apk. So if you force it to AAB, we'll ignore the `-target apk` bit and treat it as it if was `-target aab`, but the output filename will still be whatever Animate requested..

thanks
