### ISSUE TITLE
file.exists is returning false

### ISSUE THREAD

**Issue by Shaunmax** [airsdk/Adobe-Runtime-Support#2631]
Hello I am facing a strange issue with my iOS mobile app:

`private static var extAsset:File = File.applicationStorageDirectory.resolvePath("assets/assets.zip");`

the file `assets.zip` exists in the `assets` folder but when I check `if (extAsset.exists)` it always returns false ? what could be wrong ?

I use IntelliJ as the IDE to add this folder along with the build.
![image](https://user-images.githubusercontent.com/16576562/235409459-7668fd7f-903b-4691-aabf-86b516dd8cbf.png)

according to the current implementation, if `extAsset.exists == false` then download `assets.zip` from cloud storage. After downloading, I again check for `if (extAsset.exists)` and this time it gives `true` and then code proceed with unzipping. 

When I check the native path of extAsset i get this : 

`extAsset nativePath /var/mobile/Containers/Data/Application/XXXXXX-XXX-XXX-XXX-XXXXXXXXXXX/Library/Application Support/com.company.appname/Local Store/assets/assets.zip`

and it's same before and after downloading the file. 

Can somebody help me on this ?

**Comment by ajwfrost** [comment]
If you're trying to get at an `assets.zip` file that you're distributing with your application, it would be in the application directory, rather than application storage directory:
```
private static var extAsset:File = File.applicationDirectory.resolvePath("assets/assets.zip");
```
`applicationDirectory` is for the files that ship with your application, typically a read only path
`applicationStorageDirectory` is where you should put files that are private to your application

thanks
