### ISSUE TITLE
Closing main app does not closes all background processes initiated from ANE

### ISSUE THREAD

**Issue by Oldes** [airsdk/Adobe-Runtime-Support#2649]
Hi,
I am working on a native extension for Epic SDK and I noticed, that when I close the main app, there is still running a background process.
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/454805/b2baf9a9-f2d0-43e7-9d46-3e06dc27e2b0)

After closing the main app:

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/454805/6cc2abc3-3393-4466-983e-50ea9fabdd28)

It is quite possible, that I am missing some correct shutdown sequence in my extension, but anyway... maybe it is worth a note.

**Comment by Oldes** [comment]
These 2 `EOSOverlayRenderer` processes visible above also keep to be running in the background until I kill the `AirExtension.exe` process manually.

**Comment by ajwfrost** [comment]
Hi

Is the "AirExtension.exe" the AIR application, created from the ADT `bundle` target? As you say "when I close the main app", but this presumably is the main app?! Presumably it's set to shut down when you close the main window, are you able to confirm you get the window closing/closed and native application exiting events?

Are you calling the extension context 'dispose' method somewhere in this shutdown sequence?

Presumably your ANE is kicking off another thread (or maybe that's being done automatically by the Epic SDK) so I would think this needs to be manually terminated in order to allow the application to fully exit..


On the documentation -> we had created a clone of the Adobe docs but hadn't got very far in updating them to put them onto airsdk.dev .. so for now, yes that's the best place to look still.


thanks

  Andrew

**Comment by Oldes** [comment]
* Yes... it is a `bundle`.
* I am closing the main app using the close `X` button on the window.
* I will check the closing events...
* I am not calling the dispose.. I though it is automatic on close.

In the extension I have:
```C
	EOS_Platform_Release(hndlPlatform);
	EOS_Shutdown();
```
in `ExtFinalizer` and also in `ContextFinalizer`.

When I add a native `shutdown` function in my ANE and call it, the processes are closed as expected. Although for a while the app is in a not responding for a while... apparently Epic is doing some calls to their servers before closing so it takes some time:/

**Comment by Oldes** [comment]
Ok... it looks that when I use:
```
NativeApplication.nativeApplication.addEventListener(Event.EXITING, onClosing);
```
and 
```
private function onClosing(event:Event):void {
   myEpicAne.dispose();
}
```
It works as expected...
I just somehow expected, that the dispose is called automatically.

**Comment by ajwfrost** [comment]
I suspect/hope the 'dispose' method would be called automatically in normal circumstances, during the overall application exit, but because there's still a thread running with (presumably) a message loop in it, Windows keeps the application open and doesn't call the global destructors that will trigger these shutdown activities..
