### ISSUE TITLE
Windows 11 / Air runtime 33.1.1.744 : "Application requires Adobe Air version which cannot be found" on runtime install

### ISSUE THREAD

**Issue by glacambre** [airsdk/Adobe-Runtime-Support#2656]
I am running Windows 11 Pro N Version 10.0.22621 and am attempting to install the Adobe Air runtime version 33.1.1.744 downloaded from https://airsdk.harman.com/runtime . The installation fails with an error message indicating the following:
```
This application requires a version of Adobe AIR which cannot be found. Please download the latest version of the runtime from http://www.adobe.com/go/getair, or contact the application author for an updated version.
```
Installing Adobe Air 50.2.1.1 works fine, but unfortunately I really need 33.1.1.744 on this machine. Is there anything I could try in order to get this version installed?

**Comment by ajwfrost** [comment]
That error message - within the runtime installer - implies that the AIR DLL can't be loaded.. which on Windows 11 and with that version, may well be this issue:

> github-1742: Removing legacy dependency on dsound.dll to fix Win11 runtime failure

This was fixed in 33.1.1.821, so would still be an issue for the 33.1.1.74x ones....

Are you able to check on your machine to see if there's a "dsound.dll" present in the Windows\System32 folder? If not, then odds are that this is the problem...

As a potential fix, you could try installing the DirectX additional runtime files from Microsoft's website:
https://www.microsoft.com/en-us/download/details.aspx?id=35
I've not tried it but it may put on the Dsound.dll file. Or you could try to find it and copy it from a previous computer.. or potentially even just find another DLL and copy that so that it's also present with the 'Dsound.dll' filename? I believe AIR was linking with this i.e. specified it as a dependency, without actually using any functions from it (directly)...

Failing that -> we would need to issue a 33.1.1.745 to include that fix (and maybe other recent ones..) so that there's a reasonable version that can be used for folk still needing the WebKit libraries..

thanks
