### ISSUE TITLE
Build with X86 architecture on Mac

### ISSUE THREAD

**Issue by capjason** [airsdk/Adobe-Runtime-Support#2686]
## Description
I have a program built with Adobe Air SDK 22.0, and everything works fine until we encountered the fn key shortcut problem on Monterey ([#2586](https://github.com/airsdk/Adobe-Runtime-Support/issues/2586)). I tried using the newer SDK 33.1, and the issue was fixed. However, it led to another problem.

The program built with SDK 33.1 has Universal architecture, but some of the ANEs in the program are built only with x86-64 architecture, which results in a failure to load ANE on Mac with M1. Thus, I am now caught in a dilemma.

If I continue to use SDK 22.0, bug #2586 remains.
If I switch to SDK 33.1, ANE fails to load on Mac with M1.

Therefore, I am requesting that I can build my program with SDK 33.1 and force it to be built in x86_64 architecture.

I greatly appreciate it!

**Comment by ajwfrost** [comment]
I'm assuming you're creating this as an app bundle, i.e. you end up with your application as a .app file? In which case, there's a hack you can do to switch it to just x86_64 after it's built:
```
lipo AppName.app/Contents/MacOS/AppName -remove arm64 -output AppName.app/Contents/MacOS/AppName
```

You'd have to then re-sign the package, e.g. using
```
adt -sign -storetype KeychainStore -alias "Developer ID Application" -target bundle AppName.app SignedAppName.app
```

But then it should mean it's treated just as an Intel binary and will always run using Rosetta without needing to be configured.

----

The idea of being able to actually choose this so that it happens automatically within ADT is something we had wondered about though, so we can add that - probably just using the `ARCH_OPTIONS` setting when you use ADT with the `-target bundle`..

**Comment by capjason** [comment]
Thanks, @ajwfrost. The workaround works for me.

I prefer to build my app with universal support to fully utilize the capabilities of M1/M2. The problem is that the ANEs we depend on only support x86_64 and have already reached end-of-life. So, I have no choice.
