### ISSUE TITLE
[macos][50.2.3.1] EncryptedLocalStore internal error Error

### ISSUE THREAD

**Issue by pis0** [airsdk/Adobe-Runtime-Support#2722]
this issue came back in this sdk version.
 https://github.com/airsdk/Adobe-Runtime-Support/issues/2011

## Problem Description

environment:
macOS 13.4.1
Air SDK v50.3.2.1
java 11.0.11

```
 Error: EncryptedLocalStore internal error
flash.data::EncryptedLocalStore$/processErrorCode
flash.data::EncryptedLocalStore$/setItem
```

## Known Workarounds

 manually sign and notarize application

**Comment by ajwfrost** [comment]
Hi

We're not able to reproduce this with a simple test case running via ADL, using the latest AIR SDK and macOS 13.4.1 (c)
Bit - if we create a bundle from it, then we do get the internal error...
If we create a signed bundle from it (not notarised yet), we get a message pop up:
> AppName wants to use your confidential information stored in "Adobe.APS" in your keychain.
> To allow this, enter the "PrivateEncryptedDatak" keychain password.

Hitting 'Always Allow' at that point will prevent it popping up again (it's a blank password).

But yes, I thought we had previously set things up so that it wouldn't need to ask the user. We can check on this one...

thanks

**Comment by pis0** [comment]
exactly, @ajwfrost .. in my case it was needed to delete the ELS files from the ~/Library folder as well.. tks!
