### ISSUE TITLE
Can't debug from Intellij Idea in Emulator (haven't tried directly on device yet)

### ISSUE THREAD

**Issue by phitrti** [airsdk/Adobe-Runtime-Support#2760]
Probably not a bug, probably me but.... help....

I got a new MacBook switching from intel core to m2. So in setting everything up:
1. Latest intellij
2. Latest Air (50.2.3.2) + usual Flex following the usual instructions. I've had no issues in the past.
3. android sdk set up
4. openjdk 11 from intellij
5. I haven't had the time or energy to convert my build scripts away from ANT especially since I have some custom ANT tasks and they seem to still work.

The problem:
My ant script builds the app just fine from terminal. But, from intellij idea, when i try to debug the app (in the emulator if that matters),  it doesn't seem to get past the "Waiting for Player to connect". No emulator ever starts. I've searched these issues and I think I've done everything that needed to be done. Is there some way to get some insight into why I can't debug. BTW, this worked just fine on old mac (just now with the latest of everything).

I have not yet tried running directly on a device, only the emulator for now. IntelliJ output:
"/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/bin/java" -Dapplication.home=/Users/reckhoff/Desktop/Tools/tools_air/flexsdks/4.16.1_AIR50.2.3.2 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -classpath /Users/reckhoff/Desktop/Tools/tools_air/flexsdks/4.16.1_AIR50.2.3.2/lib/fdb.jar flex.tools.debugger.cli.DebugCLI -ide
Apache fdb (Flash Player Debugger) [build 20171115]
Copyright 2017 The Apache Software Foundation. All rights reserved.
Waiting for Player to connect
/Users/reckhoff/Desktop/Tools/tools_air/flexsdks/4.16.1_AIR50.2.3.2/bin/adl -profile extendedMobileDevice -screensize NexusOne -XscreenDPI 252 -XversionPlatform AND -extdir /private/var/folders/mf/4f689rp94r18qbj4ncsx1z140000gn/T/IntelliJ_ANE_unzipped /Users/reckhoff/Desktop/ProjectSource/GitHub/SMILE/MobileApps/SMILE/bin/SMILE-app.xml /Users/reckhoff/Desktop/ProjectSource/GitHub/SMILE/MobileApps/SMILE/bin

I'm sure it is something I didn't set up (I hate getting new hardware where everything has to be reinstalled), but for the life of me, I can't figure it out.

Randy

**Comment by phitrti** [comment]
my copy/paste left out:

[AIR Debug Launcher]: Process finished with exit code 137

Sorry.

**Comment by ajwfrost** [comment]
So my guess would be that the second part isn't working properly because of a bug IntelliJ have with the extraction of ANEs .. macOS have got more strict about this recently so it's causing some issues at start-up.

Simplifying this line:
```
adl -profile extendedMobileDevice -extdir tmp/IntelliJ_ANE_unzipped SMILE-app.xml bin
```
I suspect that if you can look at that "IntelliJ_ANE_unzipped" folder, you'll see a set-up where there are frameworks that were used within the ANE but these would be malformed in Apple's eyes (files instead of links).

See the workaround proposed in https://github.com/airsdk/Adobe-Runtime-Support/discussions/2581#discussioncomment-5577544 - you should be able to find that folder and manually unzip your ANEs to it, removing whatever was there first. The normal unzip command from macOS should work fine with the symbolic links..

thanks

**Comment by reckhoff** [comment]
As always, best support on the planet.

I looked at the related ticket and confirm the relation. I’ll close this ticket and track that ticket.

Fyi…. This morning (ran out of time yesterday), I ran the app directly on an android (haven’t tried iOS yet) with success so that is a bit of a work around to make it easier for team members for development. Just need to pinch a few tablets from the QA stash 😉

Randy

From: Andrew Frost ***@***.***>
Date: Thursday, August 10, 2023 at 1:46 AM
To: airsdk/Adobe-Runtime-Support ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [airsdk/Adobe-Runtime-Support] Can't debug from Intellij Idea in Emulator (haven't tried directly on device yet) (Issue #2760)
EXTERNAL:  This email originated from outside of the organization.  Do not click links or open attachments unless you recognize the sender and know the content is safe.


So my guess would be that the second part isn't working properly because of a bug IntelliJ have with the extraction of ANEs .. macOS have got more strict about this recently so it's causing some issues at start-up.

Simplifying this line:

adl -profile extendedMobileDevice -extdir tmp/IntelliJ_ANE_unzipped SMILE-app.xml bin

I suspect that if you can look at that "IntelliJ_ANE_unzipped" folder, you'll see a set-up where there are frameworks that were used within the ANE but these would be malformed in Apple's eyes (files instead of links).

See the workaround proposed in #2581 (comment)<https://github.com/airsdk/Adobe-Runtime-Support/discussions/2581#discussioncomment-5577544> - you should be able to find that folder and manually unzip your ANEs to it, removing whatever was there first. The normal unzip command from macOS should work fine with the symbolic links..

thanks

**Comment by phitrti** [comment]
closing ticket. see: https://github.com/airsdk/Adobe-Runtime-Support/discussions/2581 instead.
