### ISSUE TITLE
SSL failed using URLRequest

### ISSUE THREAD

**Issue by httpwebmedia** [airsdk/Adobe-Runtime-Support#2817]
## Problem Description

I use URLRequest on remote server using https
All of a sudden, I started to see these black screen display : 
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21228346/976c2eaa-60e8-4f00-969a-83f35b70732d)
Sorry about the french language but the first sentence says : The server your application attempts to connect is not valid.

It's an old tablet using Android 7.
On a most recent one (version 13), I don't see that display at all.

I tried with air sdk version 50.2.3.2 and 50.2.2.6 but same result...
Any thoughts?

**Comment by httpwebmedia** [comment]
New update... I'm getting the same result when I install the app from the playstore...

**Comment by FliplineStudios** [comment]
It may be related to the issue with Let's Encrypt changing their certificates which started in 2021, though maybe they've recently changed again.  There was a conversation about the changes in Issue #1228 here:
https://github.com/airsdk/Adobe-Runtime-Support/issues/1228

If it's the same issue, the main problem was that older devices didn't trust the new certificate that Let's Encrypt starting using, because it wasn't in the list of trusted stores of the OS itself back when the OS was released.  Older Android OS versions and older iOS versions never received an updated list, though newer OS versions did include their new root certificate.  

At the time it started affecting us on Android 4.x devices, and the only solution was to switch to a different SSL certificate from a different company, since the Lets Encrypt ones were no longer trusted on old devices.  Nowadays you could maybe adjust your minimum SDK/OS versions in your app so it only supports OS versions that do trust the current Let's Encrypt certificates (I believe starting with Android 8.0 and iOS 10.0)

**Comment by httpwebmedia** [comment]
Thank you very much for your help @FliplineStudios !
I use cloudflare and ended up disabling the Universal SSL and ordered advanced certificate with Google Trust Services. 
The issue is solved :)
Thank you
