### ISSUE TITLE
[Issue] Black screen android

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#2867]
In android with latest sdk 50.2.3.6 the fix of issue https://github.com/airsdk/Adobe-Runtime-Support/issues/2772 created a new issue for me.

Executing theses actions:
Take screenshot.
Swipe to show the notification bar.

Make the app go to full black screen.

## Known Workarounds
Rollback to 50.2.3.5

**Comment by ajwfrost** [comment]
Thanks, will check this, there's a few black screen related issues now and we're hoping that they may all be ultimately caused by the same sort of thing (i.e. maybe a surface is created but after the runtime thinks it's done the drawing updates..)

Will try to get this sorted out shortly.. we could of course roll back the fix for that activate/deactivate, but I think as long as we're able to fix this side-effect, it may be good to keep that one in there..

**Comment by ajwfrost** [comment]
Hi @bobaoapae  - are you able to confirm the reproduction steps here (and the device used?) - we're not able to reproduce it with these steps:
1. Launch the application
2. Screenshot via power button and volume down keys
3. Wait for the screenshot preview to disappear
4. Pull down from the top (needs pulling twice if you're using fullscreen=true) to bring down the notification centre
5. Push back up to reveal the application again

.. and a few variations of this e.g. opening the screenshot or pulling down notifications prior to it disappearing, etc.


I don't suppose you're able to put a listener for the activate/deactivate events into your code with some traces, and then run it up with an apk-debug build so that it connects to Adobe Scout? the Scout log would be quite handy here I think..

thanks

**Comment by bobaoapae** [comment]
Yeah, the adobe scout logs you want just some screenshots or the .flm file?

**Comment by bobaoapae** [comment]
@ajwfrost call you tell me what kind of logs from the Adobe scout you want?

**Comment by ajwfrost** [comment]
Hi - if you can share the FLM file that would be ideal? Let me know if you need a private link rather than posting something in public here..
thanks

**Comment by bobaoapae** [comment]
> Hi - if you can share the FLM file that would be ideal? Let me know if you need a private link rather than posting something in public here.. thanks

yes, private upload will be better

**Comment by ajwfrost** [comment]
Okay thanks -> please use https://transfer.harman.com/requests/shiSBdenBzHjefTtGTIVlb

**Comment by bobaoapae** [comment]
Send now, adobe scout logs and a screen recorder in device.
