### ISSUE TITLE
[Issue] Trojan on some machines 

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#2870]
I have a lot of users having problem with the files generated in the package process.

Windows defender detect the dll and exe files of the Adobe air captive as "bearfoos.ml"
And with avast almost all users get report of generic Trojan.

Theses alert happenen even using my own EV certify in all exe and dll files.

Also some users get the swf detected as a Trojan and get the file deleted.

Has anything that Harman can do about that?

**Comment by ajwfrost** [comment]
Hi

All the exe/dll files should be signed by us with EV certificates, which I had thought should be sufficient for Windows Defender. If there are still issues, it seems the only thing we can do is submit the binaries to Microsoft and wait for them to analyse them..  (and presumably we'd need to do this every time we make a release, for all of the exe/dll files.. so that could take a bit of time I think!)

We'll look into this, but I'm open to other ideas for it!

thanks

   Andrew

**Comment by bobaoapae** [comment]
Not all machines detect as Trojan, my own machine don't trigger in windows defender and virus total don't detect nothing. But for some reason in some machines get identified as Trojan.

Apparently some restice of old flash/Air vulnerability history that put the files in some kind of blacklis, as even the swf get identified as Trojan some times.
