### ISSUE TITLE
[Android] Custom Resources folder `<resdir>res</resdir>` not packaged using relative path (AIR 50.2.3.8)

### ISSUE THREAD

**Issue by 2jfw** [airsdk/Adobe-Runtime-Support#2922]
I'm trying to add a custom resources folder to my Android app (as described here: https://airsdk.dev/docs/tutorials/platform/android/custom-resources) but it seems that it does not work when the folder is stated _relative_ in the app-descriptor.xml.
When I set it to an absolute path, it is working as expected.

The folder structure is like this:
```
.
|____src
  __|____Application.as
  __|____Application-app.xml
  __|____res
    ____|____my_folders
```

Application-app.xml with relative path:
```
   </android>
    <resdir>res</resdir>
```

Resulting APKs `res` folder does **not** contain the content of my `res` folder.

Application-app.xml with absolute path:
```
   </android>
    <resdir>D:/dev/projects/xyz/res</resdir>
```
Resulting APKs `res` folder does contain the content of my `res` folder.

AIR SDK: 50.2.3.8
Device OS: Android 10 (1st July 2020)
Development IDE: IntelliJ 2023.2.5
Development OS: Windows 10

**Comment by ajwfrost** [comment]
The logic used here is to check if the path is available as a relative location from the process working folder; if not to try it relative to wherever the app descriptor file was found.

Can you check your adt.log file (or the AIR SDK Manager Troubleshooting tab) as we output a warning there if a file isn't found.

But also, can you please confirm what you have as "my_folders" in the above example? Because we use the Android gradle process for packaging, it will ignore anything that's not a standard Android resource folder.
See e.g. https://stackoverflow.com/questions/35073359/how-to-access-the-resource-files-under-a-self-defined-resource-directory
I just tried having a file within a "raw" folder under the "res" location and it worked:
```
|____src
__|____Application.as
__|____Application-app.xml
__|____res
____|____raw
______|____myfile.txt
```

**Comment by 2jfw** [comment]
I packed PNG icons for the distriqt Notifications ANE with the online tool mentioned in the article (https://romannurik.github.io/AndroidAssetStudio/icons-notification.html).

The `res` folder looks like this:
![content_or_res](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/91a18e3b-d8c9-4b4e-b34b-d8777884e8e5)

Referring to the very same directory with an absolute path for `resdir` will actually add the folders to the APK so I would guess the folder cannot be found when using the relative path approach - I will check and provide the adt log later on this evening as I currently cannot access my private PC.

**Comment by ajwfrost** [comment]
Okay so that folder looks okay to me, I would have thought this should work! And good point, if it's finding it with the absolute path but not with the relative path then something must be going a little wrong with the resolution; if you can provide that adt log at some point, we can see whether there are clues in that..

thanks

**Comment by 2jfw** [comment]
This is the log I generated now (I replaced a few folder names and app names for privacy):

```
*** ADT Logging at 2023/11/16 17:37:44 ***
Called by: E:\sdks\AIR_SDK_50.2.3\lib\adt.jar
ADT 50.2.3.8 called with: -version
*** ADT Logging at 2023/11/16 17:38:01 ***
Called by: E:\sdks\AIR_SDK_50.2.3\lib\adt.jar
ADT 50.2.3.8 called with: -package -target apk-debug -listen 7936 -storetype PKCS12 -keystore C:\Users\XXX\AppData\Roaming\JetBrains\IntelliJIdea2023.2\plugins\flex\lib\temp_keystore.p12 -storepass xxxxxx E:\projects\mypackage.apps\out\production\MyApplicationClient\MyApplicationClient.apk E:\projects\mypackage.apps\out\production\MyApplicationClient\MyApplicationClient-app.xml -extdir E:\externalLibs\ANE\distriqt\ANE-Notifications-master\lib -extdir E:\externalLibs\ANE\distriqt -extdir E:\externalLibs\ANE\android -C E:\projects\mypackage.apps\out\production\MyApplicationClient MyApplicationClient.swf -C E:\projects\mypackage.apps\MyApplicationClient assets
Target requested was apk-debug, but not using legacy APK so building via Android Studio
Creating device SDK handler - location passed in = C:\Users\XXX\AppData\Local\Android\Sdk
Version in APK = 50.2.3.7, version of ADT = 50.2.3.8
Gradle build where ADT is using JRE version 17.0.8.1
but where Gradle will be using the JDK from C:/Program Files/JetBrains/IntelliJ IDEA 2023.2.4/jbr\bin\java.exe
Gradle build command:  C:/Program Files/JetBrains/IntelliJ IDEA 2023.2.4/jbr\bin\java.exe -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="C:\Users\XXX\AppData\Local\Temp\61f33a52-0268-4c43-86bb-5462d7aa3adb" -cp "C:\Users\XXX\AppData\Local\Temp\61f33a52-0268-4c43-86bb-5462d7aa3adb\gradle\wrapper\gradle-wrapper.jar";"E:\sdks\AIR_SDK_50.2.3\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:assembleDebug
Does not exist: C:\Users\XXX\AppData\Local\Temp\61f33a52-0268-4c43-86bb-5462d7aa3adb/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
Creating temporary file for v2-signed APK: C:\Users\XXX\AppData\Local\Temp\61f33a52-0268-4c43-86bb-5462d7aa3adb\app\build\outputs\apk\debug\signed18442810645765491377apk
V2-signed file is at C:\Users\XXX\AppData\Local\Temp\61f33a52-0268-4c43-86bb-5462d7aa3adb\app\build\outputs\apk\debug\signed18442810645765491377apk
*** ADT Logging at 2023/11/16 17:39:00 ***
Called by: E:\sdks\AIR_SDK_50.2.3\lib\adt.jar
ADT 50.2.3.8 called with: -uninstallApp -platform android -device BH900QDJBZ -appid io.mypackage.MyApplication
Creating device SDK handler - location passed in = C:\Users\XXX\AppData\Local\Android\Sdk
Running ADB command line: C:\Users\XXX\AppData\Local\Android\Sdk\platform-tools\adb.exe -s BH900QDJBZ devices
ADB output = List of devices attached
BH900QDJBZ	device

Running ADB command line: C:\Users\XXX\AppData\Local\Android\Sdk\platform-tools\adb.exe -s BH900QDJBZ uninstall io.mypackage.MyApplication
ADB output = Success
*** ADT Logging at 2023/11/16 17:39:01 ***
Called by: E:\sdks\AIR_SDK_50.2.3\lib\adt.jar
ADT 50.2.3.8 called with: -installApp -platform android -device BH900QDJBZ -package E:/projects/mypackage.apps/out/production/MyApplicationClient/MyApplicationClient.apk
Creating device SDK handler - location passed in = C:\Users\XXX\AppData\Local\Android\Sdk
Running ADB command line: C:\Users\XXX\AppData\Local\Android\Sdk\platform-tools\adb.exe -s BH900QDJBZ devices
ADB output = List of devices attached
BH900QDJBZ	device

Running ADB command line: C:\Users\XXX\AppData\Local\Android\Sdk\platform-tools\adb.exe -s BH900QDJBZ install E:\projects\mypackage.apps\out\production\MyApplicationClient\MyApplicationClient.apk
ADB output = Performing Streamed Install
Success
```

**Comment by 2jfw** [comment]
So the following Warning/Error occurs (from `adt.log`):
`Warning: could not find file for resdir <res> (E:\projects\myApps.apps\out\production\MyApp\res)Version in APK = 50.2.3.7, version of ADT = 50.2.3.8`

**Comment by ajwfrost** [comment]
Okay thanks -> is it's looking for it under that folder (`...out\production\MyApp\res`), are you able to confirm whereabouts it actually is located? And are you running from the command line, if so what's the working directory that you're using?

Note, the APK version is based on the last build of the Android binaries; we didn't rebuild them for 50.2.3.8, so the binaries that are in AIR 50.2.3.8 will advertise themselves as 50.2.3.7. FYI there's a table in the release notes where you can see which components were included in which release, in case you're interested :-).   -> we allow differences in build number, but it wouldn't like 50.2.2.x Android binaries with 50.2.3.x build tools since there may then be binary incompatibilities introduced..

thanks

**Comment by 2jfw** [comment]
It is located here:
**E:\projects\MyApp.apps\MyApp\src\io\myPackage\MyApp\red**

I'm running from IntelliJ and the working directory (module root) is:
**E:\projects\MyApp.apps\MyApp\src\io\myPackage\MyApp\**

Okay, thanks regarding the details about the version and updated components in the release notes!

**Comment by 2jfw** [comment]
I think I should have attached the entire log for more clarity:
[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/13381119/adt.log)

**Comment by 2jfw** [comment]
Ok, with the hints from adt.log and the info that it is missing in the output/debug folder I just shifted the `res` folder to the `assets` folder, which gets packed and put in the output folder's root from IntelliJ.

The official guide states:
> This directory should be at the same level as your application descriptor, and your application swf when packaging your application.
I was not paying attention to the note that an swf is involded, which could have made me realize the `output` folder is where the `res`folder must be..

It is now working as expected; the issue was a misplaced `res` folder.
![resfolder_in_assets](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/21ac7716-638b-406d-814a-93cb1af026bc)

I initially had added the `res` folder in the Android Tab of IntelliJ and thought that this would be the way to go:
![IntelliJ project setup](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/5f1f91ef-8247-41e2-bbe0-5c8f85e0729e)

But the res folder then was always put to the APK's asset folder

**Comment by 2jfw** [comment]
Closing issue with conclusion that you need to have the `res` folder inside the `output` folder of the SWF.

In IntelliJ you would mark any folder containing the `res` folder as `Sources` like so:
![IntelliJ project setup 2](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/c361afec-f1c1-4452-a042-686e7f8d1b77)

**Comment by ajwfrost** [comment]
Okay thanks for the investigations...

So I think we have the initial problem that we're not finding the folder just as a 'relative to the working directory' because I assume IDEA is using a different working directory, or using hard-coded paths for everything, etc. 

Our back-up plan was to load the resdir value as being relative to the application descriptor file, and I guess in this instance the challenge happens because IDEA (and a couple other IDEs?) will do some pre-processing of your app descriptor file, and will then copy that into an output folder and build from there. Hence our command-line from IDEA will specify what we see as a source file (the app descriptor file) but to them it's the output file.

Not sure there's any way round this... unless IDEA gives you an option for setting a working folder. Or I don't suppose that it does other variable replacements in the XML e.g. could you use `<resdir>${SRCDIR}/res</resdir>` if IDEA is able to replace that 'SRCDIR' argument with the source code folder etc...?

But having realised why it's happening, we can have a play with IDEA to see if we come up with any ideas...

**Comment by ajwfrost** [comment]
Hi again

Could you try changing the working directory so that it's the folder below "res"?
`Run | Edit Configurations | Configuration Tab | Working Directory`

I'm hoping this would then mean that the `res` value in the app descriptor would be directly found as the right location..

thanks

**Comment by 2jfw** [comment]
>Could you try changing the working directory so that it's the folder below "res"?
>Run | Edit Configurations | Configuration Tab | Working Directory

>I'm hoping this would then mean that the res value in the app descriptor would be directly found as the right location..


In IntelliJ 2023.3 the UI may look different.
When I `Run | Edit Configurations | Configuration Tab | Working Directory` I get the following dialog:
![intellij-run](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/2094d197-e7e8-4a3a-8490-57dc3a851fbd)

There is no option to set a working directory.
There is no `Configuration Tab | Working Directory` 
`Edit Configurations` will open the above dialog.
Maybe I'm missing out something?

**Comment by ajwfrost** [comment]
Hmm, yes, looking here too and there doesn't seem to be a way to set the working folder. From a bit of debugging, IntelliJ is running the ADT command from the output folder (ideaprojects_folder/appfolder/out/production/appfolder) so if you're able to set up the 'resdir' in the tool so that it copies it over, it might be best. Only other options I can think of other than hard-coding is that we could add a manual check for this "out/production" pattern in the working folder, and if we find it (and don't manage to already find the resdir) we can then look under `../../../src` for the resdir. It's something of a hack....!

Otherwise, yes your approach of defining these like resources and ensuring they're copied over to the output folder would mean the tool picks it up automatically based on the generated app descriptor. Just a shame we don't seem to have any way to find out the actual root folder for the project, to pick this up from source..

thanks

**Comment by 2jfw** [comment]
Thanks for the additional insight on this!

Generally, it would be good to have the relative path work so it rather looks up in the "sources" and relatively to the app-desc.xml folder (as the guide of packing ressources also somehow implies) rather than reyling on data in the "output" folder.

Instead of defining the "res" folder as a ressource (in this case by adding it to the "assets" folder, which _is_ the actual defined "Ressource" in IntelliJ) it would also work to create a small batch script which copies the files over before the actual build.

Anyways, it's fine by me like it is as the work-around is easy once you know about it.

**Comment by ajwfrost** [comment]
Thanks .. although:

>  it would be good to have the relative path work so it rather looks up in the "sources" and relatively to the app-desc.xml folder

This is exactly what it does to...  but the challenge is that your "app-desc.xml" is being pre-processed by IntelliJ into a different folder, so when we get this file information, it is already in the output location. The only thing I can think of is seeing whether we can tweak the IntelliJ plug-in for how it builds the AIR apps, to pass in an extra bit of information or similar..

thanks

**Comment by cleverbeapps** [comment]
Hi @2jfw !
Did you manage to solve this problem? Could you share, please?

**Comment by 2jfw** [comment]
> Hi @2jfw ! Did you manage to solve this problem? Could you share, please?

I'm currently using an absolute path to the res folder (see first message for details)
