### ISSUE TITLE
When using SDK 50.2.4.5, error #2004 occurs in NetStream.play().

### ISSUE THREAD

**Issue by koreaflash** [airsdk/Adobe-Runtime-Support#3212]
When using NetStream.play(null) using SDK 50.2.4.5, the following error occurs.

TypeError: Error #2004: One of the parameters is invalid.
	at flash.net::NetStream/play()
	at com.kdmt.common.net::CustomStream/play()[E:\kdmtdev\rtmp\rtmp2http\src\com\kdmt\common\net\CustomStream.as:238]
	at com.kdmt.common.net::CustomStream/resume()[E:\kdmtdev\rtmp\rtmp2http\src\com\kdmt\common\net\CustomStream.as:186]
	at com.kdmt.common.player::VideoObj/_seekByTime()[E:\kdmtdev\as3_common\src\com\kdmt\common\player\VideoObj.as:495]
	at Function/http://adobe.com/AS3/2006/builtin::apply()
	at DelayObj/call()[E:\kdmtdev\as3_common\src\com\kdmt\common\pool\DelayObj.as:18]
	at com.kdmt.common.pool::DelayPool/enterFrame()[E:\kdmtdev\as3_common\src\com\kdmt\common\pool\DelayPool.as:40]

It doesn't happen on 50.2.4.4, 50.2.4.3, 50.2.4.2, etc.

The development environment is as follows.
AIR SDK: 50.2.4.5
Windows 10 Enterprise
IDE: Flashbuilder 4.7
Test Device OS : Android 13

- For reference, I am playing an flv file.
- Attach the CustomStream.as file.

![netstream_error](https://github.com/airsdk/Adobe-Runtime-Support/assets/36652089/c5045769-1873-4962-99d2-998cb5e78cdf)
[CustomStream.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/15158202/CustomStream.zip)

**Comment by itlancer** [comment]
@koreaflash
Also make sure you don't use `ns.play("");` anymore. https://github.com/airsdk/Adobe-Runtime-Support/issues/3098

**Comment by koreaflash** [comment]
I will try update the code.
Thank you.

**Comment by koreaflash** [comment]
- We provide educational content.
- Users can learn page by page and move pages freely.
=> Users can access pages containing netstream from time to time.
- There is a function to preload the front or back page of the current page.
=> Users can also use 3 netstreams at the same time.

For the above reasons, play() is called frequently.
Is there a solution...?

**Comment by ajwfrost** [comment]
Well we can change it so that play(null) is accepted as long as the previous play() calls also had the null argument. But you could just omit that call after the first time; you're calling in the reset action which would have the same effect? or is there then a delay between switching videos whilst the data already sent in is still being processed?

Previously, calling "play(null)" on a netstream which was already playing would just have reset/orphaned everything and set up a new playback pipeline. So there's not a huge difference between that and creating a new NetStream object. But we can add back in the capability, with that security check to ensure it's not being switched between different modes...

**Comment by ajwfrost** [comment]
Ah - I just checked the code, and this is actually already what it's trying to do. But the check for if the argument is "null" is failing because we're checking that after a string conversion and the object itself then comes out as a non-null object (containing a string with contents "null"!!) -> switching the check here to null-check the original argument, rather than the stringified version...

thanks

**Comment by koreaflash** [comment]
This issue has been resolved in version 51.0.1.2.
