### ISSUE TITLE
ver 51.01.4 supports till targetsdk 33 but google requires 34 till end of august

### ISSUE THREAD

**Issue by avrahamshlomo** [airsdk/Adobe-Runtime-Support#3352]
I still try to compile with target sdk 34 and i still cannot, i get errors.
did anyone compile with target sdk 34 and native extensions from airnativeextensions.com ( i use admob ads)?

unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':androidx.activity'.
> Could not open cp_proj generic class cache for build file 'C:\Users\solomon\AppData\Local\Temp\7eafcca7-1f05-4801-b9a8-c9d56ab2cec2\androidx.activity\build.gradle' (C:\Users\solomon\.gradle\caches\7.5\scripts\3xujas41tcvwajglvhukeu4yt).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':androidx.activity'.
> Could not open cp_proj generic class cache for build file 'C:\Users\solomon\AppData\Local\Temp\7eafcca7-1f05-4801-b9a8-c9d56ab2cec2\androidx.activity\build.gradle' (C:\Users\solomon\.gradle\caches\7.5\scripts\3xujas41tcvwajglvhukeu4yt).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

        at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
        at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)

**Comment by ajwfrost** [comment]
Can you set your JAVA_HOME configuration variable to point to a Java 17 runtime/JDK please? The error seems to be caused by this: `Unsupported class file major version 66` which is related to a Java build tool that can't run on the current Java runtime.

thanks

**Comment by ajwfrost** [comment]
For the adt.cfg file, it looks at `JAVA_HOME` and `AndroidPlatformSDK`. It would ignore settings like `java.home` and `android.sdk.path`, they're not used within ADT.

Your error there is `Unsupported class file major version 65` - which is a Java error saying that it can't load a Java class file because the version used (65 means Java 21) isn't supported, which implies that the Java that's being run is lower than this. So presumably the JDK-17 that you have in that JAVA_HOME variable?

ADT itself can run with a lot of different versions of Java, from 1.8 upwards, but when it needs to launch the Android build tools, it uses that JAVA_HOME value to pick up a suitable JDK. Knowing what "suitable" means is the challenge, because the tools that are used can depend upon the Android SDK and build tools that have been installed....

Generally I would say that the best option is to use the Java version that's provided by Android Studio - which is what we try to find, if you don't actually have a `JAVA_HOME` setting in the config file or environment. But it can help to explicitly point to this.

BTW those config files are read by Java `Properties` which means that all file paths need to either be forward-slashes, or escaped backslashes (i.e. `/` or `\\`), if you have single backslashes then iirc it means Java will completely ignore the whole file...

My current adt.cfg:

```
# See release notes: uncomment these lines in order to force your APK to be generated with 64-bit ARM binaries
# (needed when using an IDE such as Adobe Animate that currently only provides armv7 and x86 as the options via the UI)
#DefaultArch=armv8
#OverrideArch=x64

# See release notes and https://github.com/Gamua/Adobe-Runtime-Support/issues/58
#UncompressedExtensions=emd,tfl,tflite,pb

# Default is to prefiix the package with 'air.' - to turn this off, uncomment the below line
#AddAirToAppID=false

# If you need to increase the heap available to Java when packaging an Android app, you can use the below setting
# when ADT is run from another tool. (If run from the command line, just add -Xmx=2048m or similar to the command
# line within the ADT launch script..)
#JavaXmx=2048m

# For debugging, set this to 'true' and a file "adt.log" should be generated in your user's home folder
DebugOut=true

# To override the creation of an Android APK file, and to instead create an Android App Bundle, the below
# flag can be uncommented. Note that the bundle may end up with an "apk" file extension
CreateAndroidAppBundle=false

# When creating an Android App Bundle, this flag can be used to output the Android Studio project
# files in a subfolder of your build directory (rather than using a temporary location that gets
# cleaned up on exit).
KeepAndroidStudioOutput=true

# For convenience, rather than using "-platformsdk" on the command line, these can be set up here:
AndroidPlatformSDK=C:/Users/ukinanfr/AppData/Local/Android/Sdk
#iOSPlatformSDK=path_to_sdk

# JAVA_HOME is usually picked up from an environment variable but this can override it:
JAVA_HOME=C:/Program Files/Java/jdk-17.0.2
#JAVA_HOME=C:/Program Files/Java/jdk-11.0.2

# on macos platorms, use the native codesign task rather than trying to use ADT's internal code:
#UseNativeCodesign=true

IPALinkFolder=c:/users/ukinanfr/.airsdk/linkfolder
#RemoteLinkMachine=192.168.1.15

UseGradleCodesign=true
```

The description of these files was in the release notes, it got dropped accidentally a while back when tidying up but we've put it back in for 51.1....

**Comment by perholmes** [comment]
Hi,

I appreciate it. I've found it difficult to locate changes in release notes, because it's very important to have a PDF of every single release note, or you might miss it. Good to have the example you pasted.

Per

**Comment by ajwfrost** [comment]
> difficult to locate changes in release notes

I often use the online https://airsdk.harman.com/release_notes page with the search tool, to check when different github issues were mentioned; but yes, only very brief text descriptions in there, and no cross-referencing search to the referenced github issue itself..

**Comment by perholmes** [comment]
That's a good page, thank you!
