### ISSUE TITLE
TextField Chinese characters cannot be displayed on iOS18.

### ISSUE THREAD

**Issue by wmtj** [airsdk/Adobe-Runtime-Support#3354]
TextField Chinese characters(_sans) cannot be displayed on iOS18 beta1~3. But embed font works fine.

[AIR 51.0.1.4] with ipa remote linking on Windows 11, and older AIRSDK, all does not work.

@ajwfrost  Have you tested it? Thanks!

**Comment by wmtj** [comment]
@ajwfrost  Will this issue be fixed in the next release? iPhone users can directly choose to upgrade the iOS 18 beta version, which has caused more and more users' feedback recently that Chinese(_sans) cannot be displayed. It's so easy to reproduce the phenomenon that I didn't write the demo code, but I'll include it if needed.

**Comment by ajwfrost** [comment]
One of the the team has started looking into this one; we had planned for the iOS18 support to be checked a little later, but if there are problems like this with existing apps that don't run properly, we'll see if we can work this out with just a runtime update without having to build with it.

Slight caveat of course: we've found problems before with beta software where the problems disappeared in the next beta release, or in the production ones.

To check the use case here .. you're just creating a normal, dynamic `TextField` object, telling it to use a font via the `_sans` alias, and then setting some Chinese character codes for it? What actually appears - just nothing at all, or blank boxes, or spaces? Does it work if you set the font to an actual font that supports this e.g. via a `TextFormat("STHeitiSC-Medium")`?

**Comment by ajwfrost** [comment]
Early feedback = device text rendering - both in TextField and TextLine - is failing, even if we manually select the fonts that should work. This is going to need a bit more low-level debugging...

**Comment by wmtj** [comment]
Test code : 
`
	public class AIRSDKChineseTest extends Sprite 
	{
		[Embed(source="NSSC-R.otf", fontName="embedFont", mimeType="application/x-font-truetype", embedAsCFF="false")] 
		public static const embedFont:Class;
		
		public function AIRSDKChineseTest() 
		{
			super();
			
			Font.registerFont(embedFont);
			
			stage.align = StageAlign.TOP_LEFT;
			stage.scaleMode = StageScaleMode.NO_SCALE;
			
			addTextFields();
		}
		
		private function addTextFields():void 
		{
			var _tfmt1:TextFormat = new TextFormat("_sans", 50, 0);
			var _tfmt2:TextFormat = new TextFormat("_serif", 50, 0); 
			var _tfmt3:TextFormat = new TextFormat("STHeitiSC-Medium", 50, 0); //iOS 
			var _tfmt4:TextFormat = new TextFormat("embedFont", 50, 0); 
			
			_tfmt1.align = _tfmt2.align = _tfmt3.align = _tfmt4.align = TextFormatAlign.CENTER;
			
			
			var _txt1:TextField = new TextField();
			_txt1.defaultTextFormat = _tfmt1;
			_txt1.text = "简体中文测试（繁體中文測試）ABC";
			//_txt1.setTextFormat(_tfmt1);
			_txt1.width = _txt1.textWidth + 12;
			_txt1.height = _txt1.textHeight + 4;
			_txt1.border = true;
			_txt1.x = 100;
			_txt1.y = 200;
			addChild(_txt1);
			
			var _txt2:TextField = new TextField();
			_txt2.defaultTextFormat = _tfmt2;
			_txt2.text = "简体中文测试（繁體中文測試）ABC";
			//_txt2.setTextFormat(_tfmt2);
			_txt2.width = _txt2.textWidth + 12;
			_txt2.height = _txt2.textHeight + 4;
			_txt2.border = true;
			_txt2.x = 100;
			_txt2.y = 300;
			addChild(_txt2);
			
			var _txt3:TextField = new TextField();
			_txt3.defaultTextFormat = _tfmt3;
			_txt3.text = "简体中文测试（繁體中文測試）ABC";
			//_txt3.setTextFormat(_tfmt3);
			_txt3.width = _txt3.textWidth + 12;
			_txt3.height = _txt3.textHeight + 4;
			_txt3.border = true;
			_txt3.x = 100;
			_txt3.y = 400;
			addChild(_txt3);
			
			var _txt4:TextField = new TextField();
			_txt4.defaultTextFormat = _tfmt4;
			_txt4.embedFonts = true;
			_txt4.text = "简体中文测试（繁體中文測試）ABC";
			//_txt4.setTextFormat(_tfmt4);
			_txt4.width = _txt4.textWidth + 12;
			_txt4.height = _txt4.textHeight + 4;
			_txt4.border = true;
			_txt4.x = 100;
			_txt4.y = 500;
			addChild(_txt4);
		}
	}
`
On iOS 17.5 :
![onIOS17 5](https://github.com/user-attachments/assets/c8dc9d89-842f-4978-8c25-15797ae54a1c)

On iOS 18 beta3 :
![Uploading onIOS18beta3.PNG…]()

**Comment by wmtj** [comment]
On iOS 18 beta3 :
![onIOS18beta3](https://github.com/user-attachments/assets/840fee96-6955-4fad-a83b-47fdd1d31203)

**Comment by wmtj** [comment]
Is there any progress on this issue? @ajwfrost 
More and more iphone users began to upgrade iOS 18.1 beta version, resulting in more and more complaints about my app. Users couldn't understand 'why other apps could run normally on iOS 18', 'Why only your app can't'...I feel helpless. I couldn't explain it to them because of AIRSDK  :) 
I hope this won't be the same situation as Android 12, which caused a lot of user losses...

**Comment by ajwfrost** [comment]
We are working on this one, hoping to get a fix out within the next week or two. It's a bit of a challenge though as the APIs from Apple have changed how they work, we may need to do more rework than we had anticipated (in the same way that we had to completely rework the text rendering mechanism used on Android 12...). We have to render text at a lower level than most apps - hence the introduction of StageText, so that AIR can actually do things a bit more similarly to a normal mobile app and how the OS vendors want people to..

Will try to keep you updated here..

thanks

**Comment by ajwfrost** [comment]
Looks like Apple have made some significant changes in fonts with iOS18, particularly around the Chinese fonts! So - we may need to adjust some of the fallback mechanisms, but that was what we first tried and it hadn't helped. We've now found that they are using TTF files that don't contain the normal/official table types for glyphs, instead they appear to have invented a new table with an undocumented format to provide the Chinese glyphs.

See e.g. https://forums.developer.apple.com/forums/thread/759219

Thankfully it also looks like we can still get and render the glyphs using our existing APIs, the fallback was failing because the font file was being rejected as it's invalid. If we can accommodate that new/undocumented table, we should be able to get this sorted out.

thanks

**Comment by ajwfrost** [comment]
@wmtj  are you able to try this out with the new AIR SDK release and confirm? We double-checked the use cases that we had here, and it's working for us on 18.0 beta 5...
https://airsdk.harman.com/download/51.1.1.3

thanks

**Comment by wmtj** [comment]
@ajwfrost I did a preliminary test in my app and it seems to be working on iOS 18 beta. I'll run more tests over the next few days, and if there are any issues, I'll report back here.

Thank you and the team for your hard work !

**Comment by wmtj** [comment]
AIRSDK[51.1.1.3] works fine on iOS 18 beta. No other issues were found. @ajwfrost

**Comment by ajwfrost** [comment]
Great, thanks for confirming

**Comment by Devin-Licastro** [comment]
I've just recieved a report that some ios18 uses are seeing garbled Chinese text. Like with random characters mixed into it:

![17282882844438365697196958320275](https://github.com/user-attachments/assets/76e0b190-5e40-4972-b7b7-57c0633d197f)

I'm trying to get more information now.
Has anyone else seen this? 
Was both simplified and traditional Chinese tested before? I believe this screenshot is from a user using traditional Chinese. 

Unfortunately i don't have an ios18 test device yet

**Comment by ajwfrost** [comment]
@Devin-Licastro what version of the AIR SDK are you using here? and what sort of text fields are you using? (i.e. normal TextField, or TextBlock/TextLine? or StageText?). Plus do you use Starling and/or Feathers (and if so, which classes)?

We can double-check with Traditional Chinese (it was Simplified characters that we used earlier it seems)..

thanks

**Comment by ajwfrost** [comment]
FYI both simplified and traditional Chinese works for us on iPhone 16 / iOS 18.. if you've got a text case/app we can run here, please let us know!

**Comment by Devin-Licastro** [comment]
Thanks for checking!

The user is using air SDK 5.1.1.1.4 or 5.1.1.1.5 here, I can't tell which, unfortunately. 
Yes, it's a starling project and the textfields are starling.text.TextField with _sans font (TextFieldTextRenderer)

Not sure if it matters, but the flow of my app is:
1. Load the json language file into a Starling AssetManager from the File.applicationDirectory
2. Put the resulting asset into an object. i.e. langObj = MyAssetManager.assets.getObject("local_sc_cn");
3. Then when creating the textfield I grab the needed String from langObj

Unfortunately, I'm a bit short on info at the moment. First, we had the issues with Chinese showing up as [][][] for an iOS18 beta user, but then after updating to Air 5.1.1.1.3+ I just assumed it was fixed. (We don't have a test device yet but we didn't get any feedback from the user that it wasn't fixed) 

I've asked my CS team now to try to confirm with users if it was ever confirmed working on any iOS18 devices, and/or if it's just this one new user having an issue (and if so, what is unique about his device or OS)

I'll report back when I learn more

**Comment by Devin-Licastro** [comment]
Hey Andrew,

I have it 90% confirmed that the issue started after the users updated from iOS18.0.0 to iOS18.0.1 (released 5 days ago)
Can I ask if your test device has updated to that version?

Thank you,

**Comment by ajwfrost** [comment]
Thanks - just checked and no it looks like we were still on the initial 18.0 release. Will get this updated and checked asap!

**Comment by Ender22** [comment]
The issue is actually stranger than I first thought. 

When the textfields are first created and as long as the user does not leave the app, the Chinese text displays fine. 
i.e. for my app we can transition between screens as much as we like with no issues.

However, if you leave the app, (i.e. switch to another app for a moment, then switch back), then the next time the textfields are redrawn all the the characters get messed up.

My colleague put together a little video here showing this:
https://www.dropbox.com/scl/fi/achilybqnbr35rkg5vnl6/RPReplay_Final1728532220.mov?rlkey=oo1e9xnrm87cj3e7niox1bvxa&st=f6mxx5rn&dl=0

Unfortunately, I can't easily put together a test project these days so I am hoping it is easy to reproduce on 18.0.1 with this new info.

**Comment by Devin-Licastro** [comment]
The issue is actually stranger than I first thought.

When the textfields are first created and as long as the user does not leave the app, the Chinese text displays fine.
i.e. for my app we can transition between screens as much as we like with no issues.

However, if you leave the app, (i.e. switch to another app for a moment, then switch back), then the next time the textfields are redrawn all the the characters get messed up.

My colleague put together a little video here showing this:
https://www.dropbox.com/scl/fi/achilybqnbr35rkg5vnl6/RPReplay_Final1728532220.mov?rlkey=oo1e9xnrm87cj3e7niox1bvxa&st=f6mxx5rn&dl=0

Unfortunately, I can't easily put together a test project these days so I am hoping it is easy to reproduce on 18.0.1 with this new info.

**Comment by ajwfrost** [comment]
Hi

We've been trying this but aren't able to reproduce, with normal text fields using a mixture of different types of Chinese (traditional + simplified) plus latin characters..

Could you upload the video to the below link please, Dropbox is blocked for us; and if you are also able to share the IPA and instructions on how to test/reproduce it, we can check it a bit more..?
https://transfer.harman.com/requests/mVZ6bsjryPFh7gO3cqkPZx

thanks

**Comment by Ender22** [comment]
Hi, okay I've gone ahead and uploaded the video to the link.
 
I think the exact steps to reproduce are:
1. Ensure you are on ios 18.0.1 (we didn't have a confirmed case on 18.0 yet so I'm not sure if it happens there)
2. In the test app, either have a button that can add new Starling.text.textfield containing Simplified Chinese (and _sans font) to the screen or a way to transition back and forth between 2 screens that contain startling textfields
3. Open the app, and look at the Chinese textfields, everything will be fine
4. Switch to another app for a moment, then switch back to this app (things will still look fine)
5. Add some new textfields to the screen (or transition to the 2nd screen)
6. These newly drawn text fields will be full of gibberish characters.

In the video, it's all simplified Chinese textfields, no traditional or latin is needed to test. We are also loading all text from a json object, not sure if that matters or not. 
The video also confirms that this happens with Starling textfields and not feathers inputs (TextFieldTextEditor) as I can see some TextFieldTextEditor that do not contain the issue on one of the screens.

I can try to get you an ipa file if the above fails. 
Would it need to be made in development mode or something, or just the ipa we usually send to app store would be enough? 

I'm just in a tricky situation at the moment as my mac that I build things on unfortunately got stolen and I'm still setting up a new one. :(

**Comment by ajwfrost** [comment]
Thanks for the video.. interesting bits of garbage displaying there. I'm wondering whether this isn't actually a font-rendering issue, it may be more on the GPU side. But we're trying to reproduce using the above steps and still not able to.

It's also been reported separately under #3521 which looks like a simpler use case (but again without us being able to reproduce this) - will continue the thread there.

Sorry to hear about your mac!

**Comment by Devin-Licastro** [comment]
Hey, I'm all set up on my new mac. Please let me know if I can assist in some way for helping you guys reproduce this.
