### ISSUE TITLE
[AIR 51.1][macOS] `EncryptedLocalStore.setItem()` with `never` mode after AIR 51.0 cause internal error

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3404]
## Problem Description
`EncryptedLocalStore.setItem()` with `never` mode after AIR 51.0 usage cause internal error with AIR 51.1 for macOS.

Tested with latest AIR 51.1.1.2 with multiple different macOS devices, different OS versions and different applications.
Same issue in all cases.
There is no such issue with other platforms.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/3403
https://github.com/airsdk/Adobe-Runtime-Support/issues/3391#issuecomment-2265492219
https://github.com/airsdk/Adobe-Runtime-Support/issues/3370
https://github.com/airsdk/Adobe-Runtime-Support/issues/2253
https://github.com/airsdk/Adobe-Runtime-Support/issues/229

## Steps to Reproduce
1) Launch application with code below with any macOS device using AIR 51.0.1.4. Close application.
2) Launch the same application with code below with any macOS device using AIR 51.1.1.2.
In application manifest you should use:
```
<encryptedLocalStorage>
	<fallbackMode>never</fallbackMode>
	<storageMode>file</storageMode>
</encryptedLocalStorage>
```

Application example with sources attached.
[air51_encrypted_local_store_never_bug.zip](https://github.com/user-attachments/files/16573712/air51_encrypted_local_store_never_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.data.EncryptedLocalStore;
	import flash.utils.ByteArray;
	
	public class AIR51EncryptedLocalStoreNeverBug extends Sprite {
		
		public function AIR51EncryptedLocalStoreNeverBug() {
			EncryptedLocalStore.setItem('test', new ByteArray());//This line cause Error: EncryptedLocalStore internal error
			EncryptedLocalStore.reset();
			EncryptedLocalStore.setItem('test', new ByteArray());
		}
	}
}
```

**Actual Result:**
Exception:
```
Error: EncryptedLocalStore internal error
 at flash.data::EncryptedLocalStore$/processErrorCode()
 at flash.data::EncryptedLocalStore$/setItem()
```

**Expected Result:**
`EncryptedLocalStore` works without errors.

## Known Workarounds
none
*Use AIR 51.0.1.4 or below or don't use `never` mode for ELS.

**Comment by ajwfrost** [comment]
This is essentially a "by design" issue.

You've created an ELS file using 51.0, which uses the OS-specific key storage mechanism. And then you're running under 51.1 telling it to use a file-based key storage, and to not have any fallback mechanism in place. So it can't find the key that had been used to encrypt the file originally, hence the decryption fails and the error is thrown.

My suggestion would be always to test access to an existing ELS store with a call to setItem/getItem within a try/catch block; if it throws the error, call reset() as it implies that the previous data has been lost..

Or if you think it useful, we could do that internally i.e. if we cannot decrypt the file properly, we automatically delete it and allow the application to continue with a new store?

**Comment by itlancer** [comment]
> Or if you think it useful, we could do that internally i.e. if we cannot decrypt the file properly, we automatically delete it and allow the application to continue with a new store?

@ajwfrost
Really doesn't matter but I think that behavior should be the same across all OSes.
If we need to handle such cases within try/catch block - ok, but let it be the same for other platforms too.

**Comment by ajwfrost** [comment]
For me, the test case fails the same way on Windows as it does on macOS... it might be different if you'd previously run a test case with the fallback option: if the first time you call an ELS function with 51.1, you have the fallback set on but with file storage, then it will pick up the old key and put it in the new location, after which this use case should then work...

**Comment by itlancer** [comment]
@ajwfrost 
I found out the reason which cause that I cannot reproduce it with Windows. Indeed previously I launched application with AIR 51.1 but remove ELS files:
`c:\Users\username\AppData\Roaming\my.app.id\ELS\`
`c:\Users\username\AppData\Roaming\Adobe\AIR\ELS\my.app.id.dat`
But also I should delete `c:\Users\username\.airsdk\.els\.kuser` to "reset migration".

Honestly, my opinion - it's better to store all each AIR app specific data in their own application storage. I mean also all ELS related data in some subdirectory inside `c:\Users\username\AppData\Roaming\my.app.id\`. Not AIR related directory. It better for every application lifecycle. Especially if many AIR applications installed on the same device.

**Comment by ajwfrost** [comment]
> Honestly, my opinion - it's better to store all each AIR app specific data in their own application storage. 

That's a possibility.. and simple to change really. But it doesn't really affect this particular case .. not an ideal situation, I know, but if we're not able to get at an existing key, we're going to have this problem. I'd thought it's better to leave it as having the possibility to try something, catch the error and then call reset, rather than us automatically deleting things if we can't read them...

**Comment by itlancer** [comment]
> I'd thought it's better to leave it as having the possibility to try something, catch the error and then call reset, rather than us automatically deleting things if we can't read them...

Agree. I will close this issue.
