### ISSUE TITLE
Corrupt AndroidManifest.xml

### ISSUE THREAD

**Issue by perholmes** [airsdk/Adobe-Runtime-Support#3428]
I'm unable to install APKs generated by packaging with the latest IntelliJ/AIR, due to corruption in Android Manifest.xml.

Regardless of whether I'm creating a debug or release build, and whether or not I'm using IntelliJs toolbar buttons or selecting Package AIR Application, the Android Manifest inside the APK is corrupt:

![Screenshot 2024-08-25 184642](https://github.com/user-attachments/assets/6d7458f7-cf6a-4237-a2be-267647387e99)

![image](https://github.com/user-attachments/assets/3f752e86-fed4-40c2-8c4d-8d0f3140260f)

The options I've explored are:

* Trying with different JDKs, in case one has a text encoding issue (looks like broken UniCode).
* Trying with a decompiler tool I found which supposedly would decode "binary XML", but it also thought the file was corrupt.
* Decompiling with ApkTool, the entire output folder is fine except for this file.
* Android Studio's APK Debugger also chokes on this file, and shows similar character markings as Notepad++.
* I have NOT explored using previous AIR/Flex versions.

When you try to install it, you get the following, both via IntelliJ and via `adb install`:

```
adb: failed to install D:/Dev/AIR/Shot Designer LTS/out/production/Android Dev/Shot Designer.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl154340015.tmp/base.apk: AndroidManifest.xml] Performing Streamed Install
```

The versions used are:

* IntelliJ 2024.2.0.2
* The OpenJDK Runtime Environment (build 17.0.11+0--11852314) that comes with Android Studio (at C:\Program Files\Android\Android Studio\jbr\bin\java.exe)
* AIR 51.1.1.1 overlaid on Flex 4.16.1.
* Windows 11
* Android Studio Build Tools 35.
* Android SDK Platform Tools 35.0.2
* Android 14.0 ("UpsidedownCake") 34-ext12

**Comment by ajwfrost** [comment]
That's not an APK file, that's an Android Application Bundle. See 'BundleConfig.pb' etc. Although I would have thought that Android Studio should be able to work it out .. does it have the .apk file extension? If so, maybe rename that to .aab and see if it can read it that way? Manifest files are binary, but Android Studio can decipher them properly..

An AAB file can't be installed by ADB, there are a few steps you need to do with Android's "bundletool" jar file - or you can use `adt -installApp -package bundle.aab` where we make those calls internally in order to generate an appropriate set of APKs for your connected device. I have no idea how IDEA is trying to do the installation, it if's using ADT it should work but if it's using ADB then it won't.

As to how you're getting an AAB file rather than an APK .. do you have the configuration file with a setting such as `CreateAndroidAppBundle` set to true? This is something you can set in order to get Animate or IDEA to generate an AAB file for uploading to the Play Store, since they don't have a UI setting for that. But it shouldn't be used if you're doing local testing where you want an APK file for direct installation.

thanks

**Comment by perholmes** [comment]
Indeed it is!

I didn't realize that I had this under `<android><createAppBundle>true</createAppBundle>` in the app descriptor. I remembered it as an adt.cfg option.
