### ISSUE TITLE
[ISSUE] Crash on android

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#3515]
```
Exception java.lang.IllegalArgumentException:
  at com.adobe.fre.FREContext.dispatchStatusEventAsync
  at br.com.redesurftank.AndroidWebSocket.AndroidWebSocket.onError (AndroidWebSocket.java:102)
  at org.java_websocket.client.WebSocketClient.onWebsocketError (WebSocketClient.java:681)
  at org.java_websocket.WebSocketImpl.closeConnection (WebSocketImpl.java:565)
  at org.java_websocket.WebSocketImpl.eot (WebSocketImpl.java:617)
  at org.java_websocket.client.WebSocketClient.handleIOException (WebSocketClient.java:991)
  at org.java_websocket.client.WebSocketClient.run (WebSocketClient.java:531)
  at br.com.redesurftank.AndroidWebSocket.AndroidWebSocket.run (AndroidWebSocket.java:62)
  at java.lang.Thread.run (Thread.java:923)
  ```
  
  First of all, I need to know how that IllegalArgumentException can happen on dispatchStatusEventAsync. It don't make any sense.

The code on `AndroidWebSocket.java` it's that:

https://github.com/bobaoapae/ane-websocket/blob/master/androidNative/app/src/main/java/br/com/redesurftank/AndroidWebSocket/AndroidWebSocket.java#L92

**Comment by ajwfrost** [comment]
The `dispatchStatusEventAsync` method can throw exceptions in two scenarions:
1) "Illegal State" if we can't get at the context object -> IllegalStateException
2) "Invalid argument" if one of the arguments is null -> IllegalArgumentException

But your code doesn't look like it could hit that issue ..?! The dispatchStatusEventAsync implementation is fairly clear on this though, it's a JNI call with the two "jstring" parameters, and only if either of these is `NULL` will the invalid argument be set.

Ah .. so actually, there's a check on the result if it does have those strings, where we go further into the runtime and check a few things, and then post the message to be handled on the right thread.

So there are a few more error situations I guess:
3) if we're unable to match the context object with the native/AS3 extension object
4) if we've got a JNI problem getting at the actual string contents

My guess would be '3' .. so, are you holding open a reference to the `ExtensionContext` somewhere? It needs to be reachable from the application memory root (main class etc) so that it doesn't get garbage collected.

If it's reproducible (and you could send us an app with this) we can add more debugging into the C++ area to see what's actually going on?

thanks

**Comment by bobaoapae** [comment]
I don't know if i can reproduce that, I got this only for the reports on the playstore console, but I think could be something about the option 3 you said, as this context could be already disposed on the AS3 side due to reconnection logic... In this situation IllegalState make more sense. I will refactore the code to ignore calls to as3 apis from java side if received a previous call from as site that can cause the as3 side to be GC due to internal logic.

**Comment by bobaoapae** [comment]
Problem solved, It's the situation 3 I think, I made some validations when the extension enter a state that can be GC by Air Runtime and the crash stopped showing on crash logs. But please take a look, I think `IllegalState` will make more sense on this case, also check those others issues https://github.com/airsdk/Adobe-Runtime-Support/issues/3516

**Comment by ajwfrost** [comment]
I think they made it to be illegal argument because we don't know what the actual issue is with the context argument (essentially, the 'this' argument when you call the method in Java - it's provided as an explicit argument in JNI).

There are a host of other functions where the same internal C++ is called to get at the AS3 extension context reference, and in all of those it has the same 'illegal argument' return value if it can't find the context. So this would be quite a shift to the API.. maybe a simpler option would be if we added some error output to logcat in these scenarios, because this does signify a pretty fatal error has happened.. (and/or, we could add a method to the FRExxx functions to validate a context object? - not sure that is perfect because it might be possible for the context to disappear between one call and the next, if you're running in a different thread... but as error handling if you called that after receiving the failure, you would at least then know why!)

Will take a look at those other crashes shortly.

thanks
