### ISSUE TITLE
App crashes on older ios devices after updating the SDK to 51.1.2.1

### ISSUE THREAD

**Issue by Tuning3DT** [airsdk/Adobe-Runtime-Support#3582]
After updating the AIR SDK from 50.2.3.1 to 51.1.2.1 the app crashes on ios devices that run on older ios versions. I tried on 2 devices one is iphone 5s with ios 12.5.7 and the other is ipad 2 with ios 13.5 
AIR SDK 51.1.2.1
device os: iOS 12.5.7

the attachment is the crash log on iphone 5s 
[3DTuning-2024-10-31-103200.ips.beta.txt](https://github.com/user-attachments/files/17904165/3DTuning-2024-10-31-103200.ips.beta.txt)

**Comment by FliplineStudios** [comment]
Are you packaging on a Mac, or on a PC?  Generally you can't safely package on a PC anymore (since the later 50.2.3.x versions).  If you haven't already I'd definitely recommend switching to Mac at least for the packaging step if you want to retain compatibility with older iOS versions.

**Comment by Tuning3DT** [comment]
@FliplineStudios I'm packaging on Mac , macOS 15.1.1

**Comment by Tuning3DT** [comment]
@ajwfrost sorry for bothering you, did you have a chance to look at our issue? 
Is there anything more I should provide with?

**Comment by ajwfrost** [comment]
Hi

Sorry, I had initially assumed the same as FliplineStudios, that this was a side-effect of trying to link on Windows. But if you're using macOS then it's an odd one.

The error itself is happening because of `Symbol not found: ___chkstk_darwin` which seems to be a fairly common occurrence, caused by mismatches in the configurations/target platforms/versions... Do you have a 'minimum SDK' version specified in your app or in any ANE? And do you have the "-platformsdk" option defined when you build the IPA file?

I think if you're able to provide the ADT logging, specifically the ld64/linker command-line, we may be able to see what's going wrong here.

thanks

**Comment by Tuning3DT** [comment]
@ajwfrost thanks for replying.
the minimum sdk is 12.2
```
<key>MinimumOSVersion</key>
<string>12.2</string>
```
and the platform is set in the `adt.cfg` file 
`iOSPlatformSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk`
 
[adt.log](https://github.com/user-attachments/files/17989826/adt.log)

**Comment by premiumsB** [comment]
@Tuning3DT  Did you find any stable SDK version for IOS yet? I'm struggling to find any version right now and I build my IPA with a Mac myself.

**Comment by ajwfrost** [comment]
Hi @premiumsB  - I'm wondering whether there's a mismatch in the various settings for the versions. If you're using AIR SDK 51.1.2 or later, then our code would have been built against the 18.0 or 18.1 iPhoneOS SDK; but, I think the IPA info.plist file is likely saying that it was generated using 17.x. I've never heard of this causing an instability before, but it would be worth trying to check this!

Let me see if we can get a version of ADT that uses your platform SDK version for this..

**Comment by premiumsB** [comment]
@ajwfrost Did you get my IPA to see which iphone SDX version I used? I'm a bit confused.

**Comment by premiumsB** [comment]
@ajwfrost You are right I just compiled an IPA with windows (I could do this with my mac too but I think it would give me the same result) but I used SDK 51.1.2.1 and it give me the 17 and not the 18 as you told me

       <key>DTSDKName</key>
        <string>iphoneos17.0</string>
        <key>DTPlatformVersion</key>
        <string>17.0</string>
        
     How could I get 18 instead of 17 there?

**Comment by xxxVBxxx** [comment]
> @Tuning3DT Did you find any stable SDK version for IOS yet? I'm struggling to find any version right now and I build my IPA with a Mac myself.

Nope. I use 50.2.3.1 version, I just replaced `adt.jar` with a newer SDK's `adt.jar` and copied `lib/bouncycastle` folder from the new SDK

**Comment by FliplineStudios** [comment]
> and the platform is set in the `adt.cfg` file `iOSPlatformSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk`
> 
> [adt.log](https://github.com/user-attachments/files/17989826/adt.log)

@Tuning3DT I just noticed you're using the iPhone Simulator SDK here instead of the actual iPhone SDK, that could be a part of the problem since that shouldn't be used for appstore or adhoc builds.  And I believe the Simulator only supports back to iOS 15.0 anyway, so maybe that SDK doesn't have compatibility with older iOS versions like you were testing on.  

Have you tried pointing to the actual SDK (it should be at `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk`)?

**Comment by Tuning3DT** [comment]
> > and the platform is set in the `adt.cfg` file `iOSPlatformSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk`
> > [adt.log](https://github.com/user-attachments/files/17989826/adt.log)
> 
> @Tuning3DT I just noticed you're using the iPhone Simulator SDK here instead of the actual iPhone SDK, that could be a part of the problem since that shouldn't be used for appstore or adhoc builds. And I believe the Simulator only supports back to iOS 15.0 anyway, so maybe that SDK doesn't have compatibility with older iOS versions like you were testing on.
> 
> Have you tried pointing to the actual SDK (it should be at `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk`)?

It still crashes with the fixed iOS SDK path
`iOSPlatformSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk`
[3DTuning-2024-12-12-193723.ips.beta.txt](https://github.com/user-attachments/files/18114040/3DTuning-2024-12-12-193723.ips.beta.txt)

**Comment by ajwfrost** [comment]
It's a very odd one... I had hoped that @FliplineStudios' suggestion would work as that sounds plausible - essentially, linking against the wrong thing. 

```
Termination Description: DYLD, Symbol not found: ___chkstk_darwin | Referenced from: 3DTuning.app/3DTuning | Expected in: dyld shared cache | in 3DTuning.app/3DTuning
```

In terms of the IPA settings in the info.plist, these are actually generated by ADT itself. The one thing I've noticed in our code is that if you use the platformsdk path like you have above, the binary would have a build sdk version of 18.0 put into it, but the info.plist doesn't pick this up so would still save 17.0 (which is hard-coded into ADT).

We're doing an update where we have the sdk values updated by default to use the latest Xcode settings and the SDK values for 18.1. Might be worth checking with that, I'll upload a test version of ADT once we have it..

thanks

**Comment by ajwfrost** [comment]
Thanks @Tuning3DT  - not entirely sure why that is, but sounds good.

@premiumsB I just spotted I hadn't replied to your earlier query here:
> I just compiled an IPA with windows (I could do this with my mac too but I think it would give me the same result) but I used SDK 51.1.2.1 and it give me the 17 and not the 18 as you told me
`<key>DTPlatformVersion</key>`
`<string>17.0</string>`
 How could I get 18 instead of 17 there?

This field is actually something we put in ourselves; there is a condition for it to pick up the version from the system, which would work on a macOS computer and would only then work if you have the `-platformsdk` argument (or `iOSPlatformSDK` in the config file) set to the path of the iPhoneOS SDK that ends with the version number. Apple normally have one un-numbered and one numbered path, one is a symbolic link, but if you have the number written in the path here, we parse that and add it in.

For our next release though, we're updating to use 18.1 here (by default). I need to check that actually as I think my working mac just updated itself, will see whether we should actually also update the build machine...
