### ISSUE TITLE
i taked this fault by publish to .aab but not fault by publish 32 bit.

### ISSUE THREAD

**Issue by orcuncun** [airsdk/Adobe-Runtime-Support#3592]
i used flash develop and AIR51.1.2 SDK.

unexpected failure: Unable to run jarsigner: com.adobe.air.ADTException: Android App Bundler signing failed:
java.io.IOException: Unable to run jarsigner: com.adobe.air.ADTException: Android App Bundler signing failed:
        at com.adobe.air.apk.AABOutputStream.jarSign(AABOutputStream.java)
        at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)

APK setup creation FAILED.

Troubleshooting:
- verify AIR SDK target version in application.xml

**Comment by ajwfrost** [comment]
This looks like it's failing when calling out to 'jarsigner' - but without it giving any error outputs. Is it possible for you to run AIR SDK Manager with the troubleshooting view active, and see what it says for the line starting `AAB signer command:`? And then try to also call the same in a command prompt or terminal window, to see if that gives any hint as to the error?

thanks

**Comment by orcuncun** [comment]
I installed the new version of Android Studio, updated all SDKs and installed the manager you mentioned, the problem was solved. Is there any guidance on the benefits that the manager will bring to us? Thank you.

**Comment by ajwfrost** [comment]
Great - maybe it was the Android SDK that needed updating to make this work then.
The AIR SDK Manager has a few key benefits:
1) Allows you to download new SDKs and update existing ones without having to download whole massive zip each time
2) Allows you to change the SDK configuration settings via a user interface rather than editing config files
3) Has the ability to collect troubleshooting information from the ADT
