### ISSUE TITLE
[Mac OS Big Sur] Permission Error (3800) when requesting permission

### ISSUE THREAD

**Issue by spamshaker** [airsdk/Adobe-Runtime-Support#713]
## Problem Description

AIR SDK for MacOS - (33.1.1.406)
AIR runtime - version 33.1.1.385
System - Mac OS Big Sur 11.2.2 (same happen on Catalina)

Describe your problem in detail. Include the following information:

When I am requesting a permission using ```file.requestPermission()```
The event handler receives an event with status denied without asking for permission
![Screenshot 2021-03-01 at 21 03 09](https://user-images.githubusercontent.com/4864089/109552257-d548be80-7ad1-11eb-9a66-3ab0e35242cc.png)
This happen only when application is packed and and installed no matter if it is signed or not. Using 
```xattr -r -d com.apple.quarantine``` doesn't help.
The issue is not taking place when running with **adl**

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.
Give us a minimal example:
The minimum code to see the problem https://github.com/spamshaker/air-big-sur-permission-issue/blob/main/src/Main.as
Following repo shows makes it reproducible https://github.com/spamshaker/air-big-sur-permission-issue
### STR:
1. ```git clone https://github.com/spamshaker/air-big-sur-permission-issue && cd air-big-sur-permission-issue```
2. Install AIR runtime - version 33.1.1.385 on Mac OS Big Sur from https://airsdk.harman.com/runtime
3. Download AIR SDK for MacOS - (33.1.1.406) from https://airsdk.harman.com/download
4. Extract SDK to cloned repo root, to directory AIRSDK_MacOS
5. Open terminal in repo root
```sh
chmod +x ./AIRSDK_MacOS/bin/compc
chmod +x ./AIRSDK_MacOS/bin/adl
chmod +x ./AIRSDK_MacOS/bin/adt
chmod +x ./build.sh
chmod +x ./run.sh
./build.sh
./run.sh
```
6. Observe application and see the window opened for browsing.
7. Now run package produced by ./bin/PermissionChecker.air
8. After installation complete it will run and shows PermissionError 'Error #3800' immediately without asking for permission.

* As little code as possible. Get to the root of the problem!
* As few dependencies as possible. Did the problem pop up with Feathers? Try to reproduce it with Starling only.
* Remove any ANEs (except if they are vital for the problem).
* Include all necessary files (e.g. textures).

## Known Workarounds

Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by ajwfrost** [comment]
Yes, the problem part here is:

> Install AIR runtime - version 33.1.1.385

as that doesn't have the fix in it for the permission problem. We're looking to provide an updated version of this shared runtime, there's another update that needs to happen first though; so for the meantime, please use a "bundle" or similar so that you package the later build of the runtime from the SDK into your app.

thanks

**Comment by spamshaker** [comment]
Currently we are using Comodo code signing cert which allows to build and sign air installer 
Will it be possible to sign the application with Comodo cert https://secure.trust-provider.com/products/CodeSigningSignup1a for application with bundled runtime?
Do we need to have an AppleID now or it still can be signed by adb?

**Comment by ajwfrost** [comment]
Hi

For a bundled runtime, this would be packaged into a .app or a .dmg and these need to be signed with Apple certificates I believe..

If you're using Comodo and code-signing to create a .air package for distribution with the 'shared' runtime, we are working on the updates to this runtime that should allow us to validate these signatures, but it is somewhat complex since (a) we don't have all the source code for this area from Adobe (although they've just given us binaries to link against), and (b) their system had depended upon a certificate that's since expired... So, it's slightly open still at the moment I'm afraid!

Regarding the original problem mentioned above, with the shared runtime 33.1.1.385, we'll be pushing an update to this out hopefully within the next two weeks to also include some other fixes, so the problem with the file-access permission should be fixed at that point.

thanks

**Comment by ajwfrost** [comment]
@spamshaker I believe the original issue here with the permission error should now be resolved, hence closing this ticket. The runtime files for 33.1.1.533 will be uploaded to the website shortly if they're not already there so this should be fixed also for folk using that...
thanks
