### ISSUE TITLE
[macOS] Native extensions doesn't work with latest AIR 33.1.1.476 for Apple Silicon M1 CPUs devices

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#843]
## Problem Description
macOS native extensions doesn't work with latest AIR 33.1.1.476 for Apple Silicon M1 CPUs devices.
AIR application use default implementation from native extension (without native code) even if you have `MacOS-x86-64` implementation with native code that compiled with latest XCode 12 as universal binary (with x86_64 and arm64 support) .

Native extension packaging has been tested with macOS Catalina and macOS Big Sur Intel-based macOS devices.
Native extension itself has been tested with multiple macOS devices with Apple Silicon M1 CPU.
The same problem in all cases.
It works fine with AIR 33.1.1.444 but via Rosetta 2 emulator for x86_64 (not native).
Also it works fine with intel-based macOS devices with AIR 33.1.1.476.

There is no other platform available to package native extensions for macOS. I mean only `MacOS-x86-64` and legacy `MacOS-x86` available. No "MacOS-ARM64"/"MacOS-Universal" or something like that.

## Steps to Reproduce
Create native extension that includes `MacOS-x86-64` platform target and native macOS implementation with universal binary (compiled with x86_64 and arm64 support).
Create any AIR application that using this native extension. Bundle it for macOS. Try to launch it with macOS devices with Apple Silicon M1 CPU.

**Actual Result:**
Application will use default native extension implementation. It will not support native code.

**Expected Result:**
Application will use macOS native extension implementation. It will use universal binary with arm64 support.

## Known Workarounds
1) Use AIR 33.1.1.444.
2) May be set up `LSRequiresNativeExecution` or `LSArchitecturePriority` with `Info.plist` file
https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
Didn't tried that yet.
3) Package your macOS application with native extension (native code should be compiled as Universal binary), then copy (duplicate) folder
`APP.app/Contents/Resources/META-INF/AIR/extensions/native.extension.id/META-INF/ANE/MacOS-x86-64`
to
`APP.app/Contents/Resources/META-INF/AIR/extensions/native.extension.id/META-INF/ANE/MacOS-x86`
After that your AIR application will think that "ARM64" native implementation at the MacOS-x86 folder and will work natively.

**Comment by ajwfrost** [comment]
Interestingly, the 'universal' MacOS version of AIR with x86_64 and arm64 support is thinking that the ANE platform is just "x86". Correcting this to "x86_64" in the first instance, means that if the ANE is packaged with a universal binary within the MacOS-x86-64 platform folder, then it should work.

Not sure whether it's then worth updating the platform name to be "MacOS-Universal" for these ones... it would be a bit of a misnomer to continue with it under MacOS-x86-64 but otherwise we would need to look both for a 'universal' binary or if that wasn't found, one with the specific cpu-specific binary. And trying to look in two locations just isn't supported by how the code works currently...

So I would say the options are:
- just support universal binaries that are then stored within the MacOS-x86-64 platform target (or we can store it in a new MacOS-Universal platform to make it clearer)
or
- just support thin binaries in MacOS-x86-64 and MacOS-ARM64 platform targets.

Of course, if we did go with this second option, we could get ADT to do the packaging up of the ANE from a single universal binary.. but there would still be a lot of duplication of other files in the ANE platform folder. It's probably the most flexible option though.

**Comment by ajwfrost** [comment]
FYI as a workaround short term, just package up the ANE with the universal binary under a "MacOS-x86" platform...

**Comment by itlancer** [comment]
@ajwfrost 
Simply packaging native extension with both "MacOS-x86" and "MacOS-x86-64" platforms doesn't solve problem.
Packaged AIR application with such ANE contains only "MacOS-x86-64" implementation and native ARM64 code doesn't work. If I try to build application with native extension that have only "MacOS-x86" implementation - then application contains only "default" impelmentation without native code.

But if I add "MacOS-x86" implementation in final ".app" then it works as native ARM64. Added it as workaround in original post.

I think that AIR native extension should support new **MacOS-Universal** target. So there will no any file duplicating etc.
At the start AIR application should look for **MacOS-Universal** (if it has) and then for **MacOS-x86-64** (if doesn't have universal, for old extensions support, for example).

**Comment by itlancer** [comment]
It works correctly with latest AIR 33.1.1.533.
AIR application uses universal binary (works for x86_64 and new Apple Silicon M1 ARM CPUs) from `MacOS-x86-64` target (directory).
Thanks!
