### ISSUE TITLE
How to use dynamic framework in ane

### ISSUE THREAD

**Issue by nbyusm** [airsdk/Adobe-Runtime-Support#851]
xcode：
***.framework embed&sign 

How to embed this framework in ane

I'm in a hurry!
please help me!

**Comment by ajwfrost** [comment]
Embedding the framework is one thing - using it would be another. Do you have an ANE already, that needs to use a framework? If so then it's just a case of adding the platform options file with a `packagedDependency` item.

In case it helps: https://community.adobe.com/t5/air/ane-with-ios-embedded-custom-framework/td-p/6906671

If you're needing to call into this framework from AIR/ActionScript code, then you need to put together the ANE to start with which will mean creating the AS3 wrapper and library and then creating the ANE, with the above packaged dependency so that it links properly.

**Comment by nbyusm** [comment]
@ajwfrost This framework is dynamic

**Comment by ajwfrost** [comment]
What's the contents of `platform-ios.xml`?

**Comment by nbyusm** [comment]
@ajwfrost 
<platform xmlns="http://ns.adobe.com/air/extension/33.1"> 
    <description>openane-ly</description> 
    <copyright>LY IOS ANE</copyright>
	<sdkVersion>0.2</sdkVersion>
    <linkerOptions>
		<option>-ObjC</option>
		<option>-ios_version_min 8.0</option>
		<option>-framework CoreMotion</option>
		<option>-framework CoreGraphics</option>
		<option>-framework SystemConfiguration</option>
		<option>-framework CFNetwork</option>
		<option>-framework Security</option>
		<option>-framework CoreTelephony</option>
		<option>-framework CoreFoundation</option>
		<option>-lc++.1</option>
		<option>-lz.1</option>
		<option>-lsqlite3</option>
		<option>-lclang_rt.ios</option>
		<option>-rpath @executable_path/Frameworks</option>
    </linkerOptions>
    <packagedDependencies>
		<packagedDependency>Frameworks/LYSDK.framework</packagedDependency>
    </packagedDependencies>
</platform>

**Comment by nbyusm** [comment]
@marchbold where? In Flash Builder?
