### ISSUE TITLE
JAVA Issue - ArmV8 - Issue with Extension

### ISSUE THREAD

**Issue by speego76** [airsdk/Adobe-Runtime-Support#858]
Hello Support,

Tested on below versions, same behavior:
- AIR 33.1.1.406
- AIR 33.1.1.444
- AIR 33.1.1.476
- Windows 10 Pro
- Animate 21.0.6

I having issues with armv8, using distriqt/ANE-Dialog on some of the features the extension offer.

Some features work and some showing not supported on armv8. Distriqt support is pointing to a JAVA issue based other users reporting similar issue and showing Android logs.

I have installed a new Fresh Windows 10 Pro PC to rule out my other DEV PC potential issues or conflicts.
Clean new JAVA install with recommended version [jre1.8.0_251]:

C:\Users\pc>echo %JAVA_HOME%
C:\Program Files (x86)\Java\jre1.8.0_251\bin

C:\Users\pc>java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode, sharing)

C:\Users\pc>echo %PATH%
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files (x86)\Java\jre1.8.0_251\bin;C:\Users\pc\AppData\Local\Microsoft\WindowsApps;

I did also try the following command from ADT:

C:\Program Files\Adobe\Adobe Animate 2021\AIR33.1.1.476\bin>
adt -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore APKANE\testV8Android.p12 -storepass 123456 testV8Android.apk testV8Android-app.xml testV8Android.swf -extdir APKANE

I am able to generate the ArmV8 APK and install it, but still getting 'Not Supported' on some features.

If there a way I  can force AIR to use the PC JAVA version instead of the embedded JAVA version in AIR? Or at check what JAVA version AIR is pushing on it?

Thanks!

**Comment by ajwfrost** [comment]
Hi

AIR should use the Java command that's in your path - check the adt.bat file in that bin folder, it's just calling java to launch the adt.jar file that's in the lib folder....

When you say "Not supported" on some features, are you able to elaborate? The one thing that I am aware of is that sometimes the use of embedded assets in ANEs on Android doesn't work because of a Java compilation issue. ADT includes its own Java bytecode compiler and there appears to be an error/restriction in this.

The workaround here is to use a JDK rather than a JRE. So if you can get the Java 8 Developer Kit and set your path up so that this is used instead, it will mean ADT then uses this to do the packaging (`javac` needs to be available from the `JAVA_HOME\bin` folder)

thanks

**Comment by speego76** [comment]
Hello,

In parallel Distriqt also point me like you to use JDK which did the trick, but not with Animate, animate still generating the armv8 with 'not supported', but at least via the ADT terminal did built it properly and works fine on armv8. Thanks!
