### ISSUE TITLE
[Windows][macOS] Green strip at the bottom of some videos

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#88]
## Problem Description
Green strip appears at the bottom of some videos with Windows and macOS devices.
It has been tested with multiple AIR SDK versions to latests AIR 32.0.0.144 beta and AIR 33.0.1.228 with different Windows/macOS devices and Windows/macOS versions. Tried with simple Video object and with StageVideo.
Same problem in all cases with some H.264 (MP4) videos.
System and other video players correct playback these videos.
It works fine with Android.
`NetStream::useHardwareDecoder = true` doesn't help - video doesn't playback at all.

## Steps to Reproduce
Launch code below. Application example with sources and example of video attached.
[stagevideo_green_strip_bug.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/3537836/stagevideo_green_strip_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.net.NetConnection;
	import flash.net.NetStream;
	import flash.media.StageVideo;
	import flash.geom.Rectangle;
	import flash.events.NetStatusEvent;
	
	public class StageVideoGreenStripBug extends Sprite {
		private var nc:NetConnection;
		private var ns:NetStream;
		
		public function StageVideoGreenStripBug() {
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		private function init(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, init);
			
			nc = new NetConnection();
			nc.addEventListener(NetStatusEvent.NET_STATUS, netStatusHandler);
			nc.connect(null);
		}
		
		private function netStatusHandler(event:NetStatusEvent):void {
			trace(event.info.code);
			switch (event.info.code){
				case "NetConnection.Connect.Success":
					ns = new NetStream(nc);
					ns.addEventListener(NetStatusEvent.NET_STATUS, netStatusHandler);
					ns.client = {onMetaData:getMeta, onPlayStatus:onPlayStatus};
					var sv:StageVideo = stage.stageVideos[0];
					sv.viewPort = new Rectangle(0,0, 1280, 800);
					sv.attachNetStream(ns);
					ns.play("video.mp4");
					break;
				case "NetStream.Play.StreamNotFound":
					trace("Stream not found");
					break;
			}
		}
		
		private function getMeta(mdata:Object):void { }
		
		//Seek video to begin after complete
		private function onPlayStatus(infoObject:Object):void {
			ns.seek(0);
		}
	}
}
```

**Actual Result:**
Green strip appears at the bottom of video.
![stagevideo_green_strip_bug](https://user-images.githubusercontent.com/10899066/63645370-6c76ce00-c705-11e9-8d5c-7caac2336361.png)

**Expected Result:**
Correct video playback without green strip.

## Known Workarounds
none

**Comment by tuarua** [comment]
Also see thread. 
https://forum.starling-framework.org/d/16787-videoplayer-causing-bottom-of-video-to-blur/6
This bug was raised for AIR 18 https://tracker.adobe.com/#/view/AIR-4054613

It appears to affect videos that have a coded_height that differs from height. AIR can't handle this.
ie a HD video is actually be encoded at 1920 x **1088** as most encoders works in macroblock of 16x16. The extra 8 pixels is what appears as the green line.

**Comment by Oldes** [comment]
Here seems to be some conversation about this _green line_ issue in VLC https://mailman.videolan.org/pipermail/vlc-devel/2013-November/095302.html

**Comment by itlancer** [comment]
With latests AIR versions it works fine with macOS.
But with Windows devices we still have this issue even with AIR 31.1.1.533 BETA.

**Comment by RossD20Studios** [comment]
+1 on this issue. I'm seeing the same behavior. The playback works fine in MacOS, in Windows 10, the same video plays back with a green strip at the bottom

**Comment by RossD20Studios** [comment]
**Update:**

Workaround fix is to re-encode the video. In my case, I was trying to play a game trailer for an expo demo. The original MP4 render was generating the green line on windows. To fix it, I downloaded a 1080P version of the same video from Youtube. That removed the green line (but at the cost of video quality)

YouTube compression is pretty aggressive (original file was 289MB, new file was 42.7MB).

But, if you're in a pinch, try this! **Note:** I had to use an external converter website to actually get the 1080P version since YouTube only let's you download 720P of your own videos for some reason.

Of course, an actual code fix to AIR would be preferred :)

**Comment by ajwfrost** [comment]
Sorry, I thought we'd already solved this part. As mentioned earlier, the green lines are generally when there's a mismatch between the heights given in the video (display height vs encoded height)

Sure enough though, I just checked the original test case using the latest AIR SDK on Windows, and we're seeing the same thing. Apologies, will get this one fixed asap!

thanks

**Comment by ajwfrost** [comment]
@RossD20Studios this fix should be released in 50.2.3.5, available now...

thanks

**Comment by RossD20Studios** [comment]
Confirmed! The latest fix has resolved this issue in Windows. Thanks so
much Andrew!

**Comment by itlancer** [comment]
With latest AIR 50.2.3.5 also fixed for Windows.
Thank you!
