### ISSUE TITLE
Android App crash when binding in Editor element

### ISSUE THREAD

**Issue by 2Xpro-pop** [airsdk/Adobe-Runtime-Support#913]
Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)

**Comment by ajwfrost** [comment]
Do you have a call stack or any output from logcat so that we can see what may be happening?
Plus we'd need to know the exact build number (which we can see if you have a full logcat output)

I'm wondering from the title whether this is something that's reproducible - if so, please let us know the repro steps or ideally a test case that demonstrates the crash.

thanks

**Comment by 2Xpro-pop** [comment]
Sorry, wrong repository, sorry again :disappointed:
