### ISSUE TITLE
Adobe Animate .aab build

### ISSUE THREAD

**Issue by AmyFoosh** [airsdk/Adobe-Runtime-Support#925]
Okay, so. With the new .533 release...

Is it possible to create an .aab file exporting an .apk file with animate and uncomment the code line inside adt.cfg?~ (you know, the code line who creates an.aab file).

Should It work that way? 

And... If we use an ANE inside, should that ANE work properly too?

**Comment by ajwfrost** [comment]
Hi

Yes exactly: if you're using Animate, or another IDE where you can't select an "AAB" output type yet, then build as if you're doing an APK but uncomment the line so that you have `CreateAndroidAppBundle=true` in your config file.

So then it's basically as if the request from Animate was switched from `-target apk -arch whatever` to `-target aab` with the rest of the params unchanged.

ANEs should work fine now because we've changed how we're doing these, the classes are being compiled and linked properly with Gradle rather than just the separate resource-bundling and code-linking that we had done before (where it lost the ability to reference resources in ANEs via the 'R.strings.id' sort of mechanism).

The only thing to watch out for might be that an AAB includes all four CPU types: armv7, armv8, x86 and x86_64. So someone with a x86_64 device can now get the proper native support when they download your app: but if the ANE only included armv7 and armv8 support then they'll not get the platform-specific ANE functionality, they'll just get the 'default' code.

thanks

**Comment by idanasher** [comment]
Regarding this issue.

I am also using animate to compile, for years now.

Do I have to use this new aat feature ? 
Or is it only apply to large apps that uses bundle ?

**I am about to distribute my new app apk to the store, 
compiled with animate and air the beta  33.1.1.533 SDK and using latest distriqt ane's.** 

Do I have to be worry about this crashing on some devices going to production with this now ? 

Thanks Andrew & Everybody

**Comment by leossmith** [comment]
@idanasher in August 2021 this will become mandatory for all new apps and in November 2021 for updating older apps.

**Comment by Gokulv617** [comment]
I'm using the latest version of Adobe Animate v21.0.7 but there is no option to select .aab publishing format in the UI. Please let me know when this option will be available(like they did for creating 64 bit apk in UI itself) in ANIMATE ?

![img_20210628](https://user-images.githubusercontent.com/43432782/123599395-2c0d9d00-d813-11eb-9f4a-b18ef258149d.png)

**Comment by idanasher** [comment]
@Gokulv617 See andrew's post https://github.com/airsdk/Adobe-Runtime-Support/issues/925#issuecomment-869107708

**Comment by ajwfrost** [comment]
And for completeness: I don't know when Adobe Animate might be updated to add in the UI for this, they're aware of the change here but of course will need time to react to this and implement an update within their standard release cycle. Hence the workaround mentioned above...

**Comment by Gokulv617** [comment]
> @Gokulv617 See andrew's post [#925 (comment)](https://github.com/airsdk/Adobe-Runtime-Support/issues/925#issuecomment-869107708)

yes will try that also. thanks

**Comment by Gokulv617** [comment]
> And for completeness: I don't know when Adobe Animate might be updated to add in the UI for this, they're aware of the change here but of course will need time to react to this and implement an update within their standard release cycle. Hence the workaround mentioned above...

okay. Thanks for updating me
