### ISSUE TITLE
NativeProcess and workingDirectory SDK 33.1.1.533

### ISSUE THREAD

**Issue by myflashlab** [airsdk/Adobe-Runtime-Support#937]
When upgraded to 533, I noticed that my nativeProcess don't work if they are anywhere outside `File.applicationStorageDirectory` it throws:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
```

Is there anything I'm missing?
```actionscript
var nativeProcessStartupInfo:NativeProcessStartupInfo = new NativeProcessStartupInfo();
nativeProcessStartupInfo.workingDirectory = File.desktopDirectory.resolvePath("tmp"); // no longer works
//nativeProcessStartupInfo.workingDirectory = File.applicationStorageDirectory.resolvePath("tmp"); // works normally
nativeProcessStartupInfo.executable = new File('/bin/bash');
		
var processArgs:Vector.<String> = new Vector.<String>();
processArgs.push("-c");
processArgs.push("bash config.sh \"" + $params.join("\" \"") + "\"");
nativeProcessStartupInfo.arguments = processArgs;
		
_process = new NativeProcess();
_process.addEventListener(ProgressEvent.STANDARD_OUTPUT_DATA, onOutputData);
_process.addEventListener(ProgressEvent.STANDARD_ERROR_DATA, onErrorData);
_process.addEventListener(NativeProcessExitEvent.EXIT, onExit);
_process.addEventListener(IOErrorEvent.STANDARD_OUTPUT_IO_ERROR, onIOError);
_process.addEventListener(IOErrorEvent.STANDARD_ERROR_IO_ERROR, onIOError);
_process.start(nativeProcessStartupInfo);
```

**Comment by ajwfrost** [comment]
I was going to say that this is a permissions issue, but a quick check shows that we can write a new file to the "tmp" folder there .. but we get the same output from the shell (trying on Big Sur...)

Will ask someone to check what's happening under the hood...

thanks

**Comment by myflashlab** [comment]
FYI: The problem is still there in `33.1.1.554`

**Comment by ajwfrost** [comment]
Hi @myflashlab  - I just checked on this, apparently this does seem to be a macOS restriction.

To get it to work:
- open System Preferences, then Security & Privacy
- select the Privacy tab and click on the lock to make changes
- choose the 'Full Disk Access' entry and the + button to browse for your application
- once added, click the lock again and close the dialog

Even if we have access to the folder for writing files etc, this still doesn't seem enough to be able to call a process from there, so it appears that 'full disk access' is needed rather than just having access to the specific Desktop folder etc..


thanks

**Comment by myflashlab** [comment]
Thanks. yeah, that solved the problem :) It's creepy to ask users to do that step manually though.

**Comment by myflashlab** [comment]
For anyone who might be interested... You can open that location in a Mac from your AIR software if you run the following command in using `NativeProcess`

```
open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"
```
