### ISSUE TITLE
Is it possible for ane to support aar?

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#959]
Sdk generally provides in aar format,convert aar to jar is not an easy task.Is it possible for ane to support aar?

**Comment by ajwfrost** [comment]
Possibly... we just started a discussion topic around this, please see #956 

thanks

**Comment by ydkgame** [comment]
Can this be achieved?

**Comment by ajwfrost** [comment]
Can I just double-check what you mean here: by "support AAR" do you mean that it should be possible for you to create an AAR containing the implementation of an ANE, and then to package this up as a .ane file rather than having to extract the .jar file from this?
Or do you mean that an ANE should be able to specify a third-party AAR file as a dependency in its platform options?

I think our only slight concern here is that there may be some Gradle limitations when trying to compile with .aar dependencies but as long as everything is specified correctly, it will probably be possible. The updates to Android ANE mechanisms are planned for the near future..

**Comment by ydkgame** [comment]
Thank you and look forward to this great function
